Kondakov_LR5_Hotel: FamilyRoom Class Reference
FamilyRoom Class Reference final
Класс семейного номера, наследует Room и ChildCare.
#include <kondakov_lr5_family_room.h>
Public Member Functions
virtual ~FamilyRoom ()=default
Деструктор
Конструкторы
FamilyRoom ()
Конструктор по умолчанию
FamilyRoom (int room_number, int child_beds)
Базовый конструктор
FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit)
Конструктор с удобствами по умолчанию
FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit, string amenities)
Конструктор с параметрами (удобства в строке)
FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit, vector< string > amenities)
Конструктор с параметрами (удобства в векторе)
FamilyRoom (const FamilyRoom &)=default
Конструктор копирования
FamilyRoom & operator= (const FamilyRoom &)=default
FamilyRoom (FamilyRoom &&other) noexcept
Конструктор перемещения
FamilyRoom & operator= (FamilyRoom &&) noexcept=default
Геттеры
int get_child_beds () const
Получить количество детских кроватей
bool get_toy_kit () const
Получить наличие набора игрушек
virtual const vector< string > & get_amenities () const override
Получить список удобств
virtual string get_full_name () const override
Получить полное название комнаты
Сеттеры
void set_child_beds (int child_beds)
Установить количество детских кроватей
void set_toy_kit (bool toy_kit)
Установить наличие набора игрушек
void set_amenities (vector< string > amenities)
Установить список удобств
Методы ввода
bool input_child_beds ()
Ввод количества детских кроватей
bool input_toy_kit ()
Ввод наличия набора игрушек
template<char Delim = ','>
bool input_amenities ()
Ввод удобств с разделителем
Переопределенные методы
virtual const string & get_room_type () const override
Получить тип комнаты
virtual const string & get_json_type () const override
Получить тип для JSON.
virtual float calculate_total (int night_count) const override
Расчет общей стоимости проживания
virtual bool validate () const override
Проверка валидности номера
Дополнительные методы
void add_play_area ()
Активировать игровую зону
void remove_play_area ()
Деактивировать игровую зону
JSON методы
virtual json to_json () const override
Преобразование в JSON.
virtual void from_json (const json &j) override
Загрузка из JSON.
Операторы доступа по индексу
string operator[] (int index) const
Оператор доступа по индексу (строковая версия)
template<typename T>
enable_if_t< is_same_v< T, float >, T > operator[] (int index) const
Шаблонный оператор доступа по индексу (const)
template<typename T>
enable_if_t< is_same_v< T, bool >, T > operator[] (int index) const
template<typename T>
enable_if_t< is_same_v< T, int >, T > operator[] (int index) const
template<typename T>
enable_if_t< is_same_v< T, string >, T > operator[] (int index) const
template<typename T>
enable_if_t< is_same_v< T, float >, T & > operator[] (int index)
Шаблонный оператор доступа по индексу (non-const)
template<typename T>
enable_if_t< is_same_v< T, bool >, T & > operator[] (int index)
template<typename T>
enable_if_t< is_same_v< T, int >, T & > operator[] (int index)
template<typename T>
enable_if_t< is_same_v< T, string >, T & > operator[] (int index)
Public Member Functions inherited from Room
virtual ~Room ()=default
Виртуальный деструктор
operator string () const
Преобразование в строку
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, ostream & > friend operator<< (ostream &os, const Container &rooms)
Перегрузка вывода для контейнера комнат
Room ()
Конструктор по умолчанию
Room (int room_number)
Конструктор преобразования
Room (int room_number, float price_per_night, bool is_booked)
Основной конструктор с параметрами
Room (const Room &)=default
Конструктор копирования
Room & operator= (const Room &)=default
Room (Room &&other) noexcept
Конструктор перемещения
Room & operator= (Room &&) noexcept=default
int get_room_number () const
Получить номер комнаты
float get_price_per_night () const
Получить цену за ночь
bool get_is_booked () const
Получить статус бронирования
void set_room_number (int room_number)
Установить номер комнаты
void set_price_per_night (float price_per_night)
Установить цену за ночь
void set_is_booked (bool is_booked)
Установить статус бронирования
bool input_room_number ()
Ввод номера комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, int >, bool > input_room_number (const Container &room_numbers)
Ввод номера комнаты с проверкой уникальности
bool input_price_per_night ()
Ввод цены за ночь
bool input_is_booked ()
Ввод статуса бронирования
Public Member Functions inherited from ChildCare
~ChildCare ()=default
Деструктор
operator string () const
Преобразование в строку
ChildCare ()
Конструктор по умолчанию
ChildCare (bool has_child_care)
Конструктор преобразования
ChildCare (float child_care_price, bool has_child_care)
Основной конструктор с параметрами
ChildCare (const ChildCare &)=default
Конструктор копирования
ChildCare & operator= (const ChildCare &)=default
ChildCare (ChildCare &&other) noexcept
Конструктор перемещения
ChildCare & operator= (ChildCare &&) noexcept=default
float get_child_care_price () const
Получить стоимость услуг для детей
bool get_has_child_care () const
Получить наличие услуг для детей
void set_child_care_price (float child_care_price)
Установить стоимость услуг для детей
void set_has_child_care (bool has_child_care)
Установить наличие услуг для детей
bool input_child_care_price ()
Ввод стоимости услуг для детей
bool input_has_child_care ()
Ввод наличия услуг для детей
Friends
Операторы сложения удобств
vector< string > operator+ (const FamilyRoom &fr1, const FamilyRoom &fr2)
vector< string > operator+ (const vector< string > &amenities, const FamilyRoom &fr)
vector< string > operator+ (const FamilyRoom &fr, const vector< string > &amenities)
vector< string > & operator+= (vector< string > &amenities, const FamilyRoom &fr)
FamilyRoom & operator+= (FamilyRoom &fr, const vector< string > &amenities)
FamilyRoom & operator+= (FamilyRoom &fr, const string &amenities)
Friends inherited from Room
Friends inherited from ChildCare
Преобразования и ввод/вывод
operator string () const
Преобразование в строку
virtual void print () const override
Вывод информации о номере
virtual bool input () override
Ввод информации о номере
virtual string to_string () const override
Преобразование в строку
ostream & operator<< (ostream &os, const FamilyRoom &r)
Оператор вывода
istream & operator>> (istream &is, FamilyRoom &r)
Оператор ввода
Additional Inherited Members
Static Public Attributes inherited from Room
static const string CURRENCY = "руб."
Валюта для отображения цен
Static Public Attributes inherited from ChildCare
static const string CURRENCY = "руб."
Валюта для отображения цен
Protected Member Functions inherited from ChildCare
void print () const
Вывод информации об услугах
bool input ()
Ввод информации об услугах
Protected Attributes inherited from Room
int room_number
Номер комнаты
float price_per_night
Цена за ночь
bool is_booked
Статус бронирования
Protected Attributes inherited from ChildCare
float child_care_price
Стоимость услуг для детей (в рублях)
bool has_child_care
Флаг наличия услуг для детей
Detailed Description
Класс семейного номера, наследует Room и ChildCare.
Definition at line 20 of file kondakov_lr5_family_room.h.
Constructor & Destructor Documentation
FamilyRoom() [1/6]
FamilyRoom::FamilyRoom ()
Конструктор по умолчанию
Создает семейный номер с параметрами:
Номер комнаты: 0
Цена за ночь: 0.0
Статус бронирования: нет
Стоимость услуг для детей: 0.0
Наличие услуг для детей: нет
Детских кроватей: 0
Набор игрушек: нет
Список удобств: "Wi-Fi", "Air condition"
Definition at line 15 of file kondakov_lr5_family_room.cpp.
References ChildCare::ChildCare(), and Room::Room().
Referenced by FamilyRoom(), FamilyRoom(), FamilyRoom(), operator<<, operator>>, and ~FamilyRoom().
FamilyRoom() [2/6]
FamilyRoom::FamilyRoom (int room_number, int child_beds)
Базовый конструктор
Конструктор преобразования
Parameters
room_number Номер комнаты
child_beds Количество детских кроватей
Создает семейный номер с указанными параметрами:
Цена за ночь: 0.0
Статус бронирования: нет
Стоимость услуг для детей: 0.0
Наличие услуг для детей: нет
Набор игрушек: нет
Список удобств: "Wi-Fi", "Air condition"
Parameters
room_number Номер комнаты
child_beds Количество детских кроватей
Definition at line 28 of file kondakov_lr5_family_room.cpp.
References ChildCare::ChildCare(), Room::Room(), and Room::room_number.
FamilyRoom() [3/6]
FamilyRoom::FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit)
Конструктор с удобствами по умолчанию
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Набор игрушек
Создает семейный номер с указанными параметрамис и удобствами по умолчанию: "Wi-Fi", "Air condition"
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Наличие набора игрушек
Definition at line 46 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, FamilyRoom(), ChildCare::has_child_care, Room::is_booked, Room::price_per_night, and Room::room_number.
FamilyRoom() [4/6]
FamilyRoom::FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit, string amenities)
Конструктор с параметрами (удобства в строке)
Конструктор с параметрами (удобства строка)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Набор игрушек
amenities Удобства (строка, разделитель - запятая)
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Наличие набора игрушек
amenities Список удобств (строка, разделитель - запятая)
Definition at line 64 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, ChildCare::ChildCare(), ChildCare::has_child_care, Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
FamilyRoom() [5/6]
FamilyRoom::FamilyRoom (int room_number, float price_per_night, bool is_booked, float child_care_price, bool has_child_care, int child_beds, bool toy_kit, vector< string > amenities)
Конструктор с параметрами (удобства в векторе)
Конструктор с параметрами (удобства вектор)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Набор игрушек
amenities Удобства (вектор строк)
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
child_care_price Стоимость услуг для детей
has_child_care Наличие услуг для детей
child_beds Количество детских кроватей
toy_kit Наличие набора игрушек
amenities Список удобств (вектор строк)
Definition at line 86 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, ChildCare::ChildCare(), ChildCare::has_child_care, Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
FamilyRoom() [6/6]
FamilyRoom::FamilyRoom (FamilyRoom && other) noexcept
Конструктор перемещения
Parameters
other Другой объект FamilyRoom
Definition at line 100 of file kondakov_lr5_family_room.cpp.
References ChildCare::ChildCare(), FamilyRoom(), and Room::Room().
Member Function Documentation
add_play_area()
void FamilyRoom::add_play_area () inline
Активировать игровую зону
Добавляет 1500 руб. к стоимости и устанавливает флаг наличия игрушек
Definition at line 148 of file kondakov_lr5_family_room.hpp.
References Room::price_per_night.
Referenced by ~FamilyRoom().
calculate_total()
float FamilyRoom::calculate_total (int night_count) const inline override virtual
Расчет общей стоимости проживания
Parameters
night_count Количество ночей
Returns
Общая стоимость (цена * ночи + 1000 руб./ребенок)
Implements Room.
Definition at line 132 of file kondakov_lr5_family_room.hpp.
References Room::price_per_night.
Referenced by ~FamilyRoom().
from_json()
void FamilyRoom::from_json (const json & j) override virtual
Загрузка из JSON.
Parameters
j JSON объект с данными номера
Implements Room.
Definition at line 128 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, ChildCare::has_child_care, Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~FamilyRoom().
get_amenities()
const vector< string > & FamilyRoom::get_amenities () const inline override virtual
Получить список удобств
Returns
Константная ссылка на вектор удобств
Implements Room.
Definition at line 35 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
get_child_beds()
int FamilyRoom::get_child_beds () const inline
Получить количество детских кроватей
Returns
Количество детских кроватей
Definition at line 19 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
get_full_name()
string FamilyRoom::get_full_name () const inline override virtual
Получить полное название комнаты
Returns
Строка вида "Семейная комната №X"
Implements Room.
Definition at line 43 of file kondakov_lr5_family_room.hpp.
References Room::room_number.
Referenced by to_string(), and ~FamilyRoom().
get_json_type()
const string & FamilyRoom::get_json_type () const inline override virtual
Получить тип для JSON.
Returns
Константная ссылка на строку с типом
Implements Room.
Definition at line 123 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
get_room_type()
const string & FamilyRoom::get_room_type () const inline override virtual
Получить тип комнаты
Returns
Константная ссылка на строку с типом
Implements Room.
Definition at line 115 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
get_toy_kit()
bool FamilyRoom::get_toy_kit () const inline
Получить наличие набора игрушек
Returns
true если набор есть, false если нет
Definition at line 27 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
input()
bool FamilyRoom::input () override virtual
Ввод информации о номере
Returns
true если ввод отменен, false если успешен
Reimplemented from Room.
Definition at line 243 of file kondakov_lr5_family_room.cpp.
References ChildCare::input(), and Room::input().
Referenced by ~FamilyRoom().
input_amenities()
template<char Delim> bool FamilyRoom::input_amenities () inline
Ввод удобств с разделителем
Template Parameters
Delim Разделитель (по умолчанию ',')
Returns
true если ввод отменен, false если успешен
Definition at line 103 of file kondakov_lr5_family_room.hpp.
Referenced by operator>>, and ~FamilyRoom().
input_child_beds()
bool FamilyRoom::input_child_beds () inline
Ввод количества детских кроватей
Returns
true если ввод отменен, false если успешен
Note
Использует оператор [] для доступа к полю
Definition at line 78 of file kondakov_lr5_family_room.hpp.
References InputControl::input().
Referenced by operator>>, and ~FamilyRoom().
input_toy_kit()
bool FamilyRoom::input_toy_kit () inline
Ввод наличия набора игрушек
Returns
true если ввод отменен, false если успешен
Note
Использует оператор [] для доступа к полю
Definition at line 90 of file kondakov_lr5_family_room.hpp.
References InputControl::input().
Referenced by operator>>, and ~FamilyRoom().
operator string()
FamilyRoom::operator string () const explicit
Преобразование в строку
Definition at line 200 of file kondakov_lr5_family_room.cpp.
operator[]() [1/9]
template<typename T> enable_if_t< is_same_v< T, float >, T & > FamilyRoom::operator[] (int index)
Шаблонный оператор доступа по индексу (non-const)
Template Parameters
T Тип возвращаемого значения
Parameters
index Индекс поля (0-4)
Returns
Ссылка на запрошенное поле
Exceptions
invalid_argument Если индекс не соответствует типу
Definition at line 209 of file kondakov_lr5_family_room.hpp.
References ChildCare::child_care_price.
operator[]() [2/9]
template<typename T> enable_if_t< is_same_v< T, bool >, T & > FamilyRoom::operator[] (int index)
Definition at line 216 of file kondakov_lr5_family_room.hpp.
operator[]() [3/9]
template<typename T> enable_if_t< is_same_v< T, int >, T & > FamilyRoom::operator[] (int index)
Definition at line 224 of file kondakov_lr5_family_room.hpp.
operator[]() [4/9]
template<typename T> enable_if_t< is_same_v< T, string >, T & > FamilyRoom::operator[] (int index)
Definition at line 231 of file kondakov_lr5_family_room.hpp.
operator[]() [5/9]
string FamilyRoom::operator[] (int index) const
Оператор доступа по индексу (строковая версия)
Parameters
index Индекс поля (0-4)
Returns
Строковое представление запрошенного поля
Exceptions
out_of_range Если индекс вне диапазона
Definition at line 145 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, and ChildCare::has_child_care.
operator[]() [6/9]
template<typename T> enable_if_t< is_same_v< T, float >, T > FamilyRoom::operator[] (int index) const
Шаблонный оператор доступа по индексу (const)
Template Parameters
T Тип возвращаемого значения
Parameters
index Индекс поля (0-4)
Returns
Значение запрошенного поля
Exceptions
invalid_argument Если индекс не соответствует типу
Definition at line 173 of file kondakov_lr5_family_room.hpp.
References ChildCare::child_care_price.
operator[]() [7/9]
template<typename T> enable_if_t< is_same_v< T, bool >, T > FamilyRoom::operator[] (int index) const
Definition at line 180 of file kondakov_lr5_family_room.hpp.
operator[]() [8/9]
template<typename T> enable_if_t< is_same_v< T, int >, T > FamilyRoom::operator[] (int index) const
Definition at line 188 of file kondakov_lr5_family_room.hpp.
operator[]() [9/9]
template<typename T> enable_if_t< is_same_v< T, string >, T > FamilyRoom::operator[] (int index) const
Definition at line 195 of file kondakov_lr5_family_room.hpp.
print()
void FamilyRoom::print () const override virtual
Вывод информации о номере
Reimplemented from Room.
Definition at line 235 of file kondakov_lr5_family_room.cpp.
References to_string().
Referenced by ~FamilyRoom().
remove_play_area()
void FamilyRoom::remove_play_area () inline
Деактивировать игровую зону
Убирает 1500 руб. из стоимости, если игровая зона была активна
Definition at line 157 of file kondakov_lr5_family_room.hpp.
References Room::price_per_night.
Referenced by ~FamilyRoom().
set_amenities()
void FamilyRoom::set_amenities (vector< string > amenities) inline
Установить список удобств
Parameters
amenities Новый список удобств
Definition at line 69 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
set_child_beds()
void FamilyRoom::set_child_beds (int child_beds) inline
Установить количество детских кроватей
Parameters
child_beds Новое количество кроватей
Definition at line 53 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
set_toy_kit()
void FamilyRoom::set_toy_kit (bool toy_kit) inline
Установить наличие набора игрушек
Parameters
toy_kit Новое значение наличия набора
Definition at line 61 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
to_json()
json FamilyRoom::to_json () const override virtual
Преобразование в JSON.
Returns
JSON объект с данными номера
Implements Room.
Definition at line 111 of file kondakov_lr5_family_room.cpp.
References ChildCare::child_care_price, ChildCare::has_child_care, Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~FamilyRoom().
to_string()
string FamilyRoom::to_string () const override virtual
Преобразование в строку
Returns
Полное строковое представление номера
Reimplemented from Room.
Definition at line 259 of file kondakov_lr5_family_room.cpp.
References get_full_name(), ChildCare::to_string(), and Room::to_string().
Referenced by print(), and ~FamilyRoom().
validate()
bool FamilyRoom::validate () const inline override virtual
Проверка валидности номера
Returns
true если количество детских кроватей <= 4, иначе false
Implements Room.
Definition at line 140 of file kondakov_lr5_family_room.hpp.
Referenced by ~FamilyRoom().
Friends And Related Symbol Documentation
operator+ [1/3]
vector< string > operator+ (const FamilyRoom & fr, const vector< string > & amenities) friend
Definition at line 175 of file kondakov_lr5_family_room.cpp.
operator+ [2/3]
vector< string > operator+ (const FamilyRoom & fr1, const FamilyRoom & fr2) friend
Definition at line 163 of file kondakov_lr5_family_room.cpp.
operator+ [3/3]
vector< string > operator+ (const vector< string > & amenities, const FamilyRoom & fr) friend
Definition at line 169 of file kondakov_lr5_family_room.cpp.
operator+= [1/3]
FamilyRoom & operator+= (FamilyRoom & fr, const string & amenities) friend
Definition at line 191 of file kondakov_lr5_family_room.cpp.
operator+= [2/3]
FamilyRoom & operator+= (FamilyRoom & fr, const vector< string > & amenities) friend
Definition at line 186 of file kondakov_lr5_family_room.cpp.
operator+= [3/3]
vector< string > & operator+= (vector< string > & amenities, const FamilyRoom & fr) friend
Definition at line 181 of file kondakov_lr5_family_room.cpp.
operator<<
ostream & operator<< (ostream & os, const FamilyRoom & r) friend
Оператор вывода
Parameters
os Поток вывода
fr Комната для вывода
Returns
Поток вывода
Definition at line 214 of file kondakov_lr5_family_room.cpp.
References FamilyRoom().
operator>>
istream & operator>> (istream & is, FamilyRoom & r) friend
Оператор ввода
Parameters
is Поток ввода
fr Комната для ввода
Returns
Поток ввода
Definition at line 225 of file kondakov_lr5_family_room.cpp.
References FamilyRoom(), input_amenities(), input_child_beds(), and input_toy_kit().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_family_room.h
Kondakov_LR5_Hotel/kondakov_lr5_family_room.cpp
Kondakov_LR5_Hotel/kondakov_lr5_family_room.hpp