Kondakov_LR5_Hotel: Kondakov_LR5_Hotel/kondakov_lr5_main.cpp File Reference
kondakov_lr5_main.cpp File Reference
Главный файл приложения для управления гостиничными номерами
#include "kondakov_lr5_methods.h"
Functions
int main ()
Точка входа в приложение
Detailed Description
Главный файл приложения для управления гостиничными номерами
Author
Kondakov Fedor
Date
2025
Version
1.0
Definition in file kondakov_lr5_main.cpp.
Function Documentation
main()
int main ()
Точка входа в приложение
Returns
Код завершения программы (0 - успешно)
Основные функции программы:
Инициализация системы (установка локали)
Создание и загрузка данных о комнатах
Формирование главного меню
Обработка пользовательского ввода
Сохранение данных при завершении
Главное меню приложения
Содержит следующие пункты:
Просмотр списка комнат
Добавление новых комнат (подменю)
Редактирование существующих комнат
Удаление комнат
Сортировка комнат
Расчет стоимости проживания
Проверка валидности комнат
Дополнительные операции
Сохранение данных
Загрузка данных
Definition at line 22 of file kondakov_lr5_main.cpp.
References Methods::add_room(), Methods::additional_room_methods(), Methods::calculate_total(), Methods::delete_room(), Methods::edit_room(), Serializer::load_rooms_from_file(), MenuObject::process(), Serializer::save_rooms_to_file(), Methods::show_rooms(), Methods::sort_rooms(), and Methods::validate_room().