Kondakov_LR5_Hotel: Kondakov_LR5_Hotel/kondakov_lr5_methods.hpp File Reference
kondakov_lr5_methods.hpp File Reference
Функции для работы с комнатами
Реализация методов работы с комнатами
#include "kondakov_lr5_methods.h"
Functions
template<typename RoomPtr, typename Container>
enable_if_t< is_base_of_v< Room, typename RoomPtr::element_type > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, vector< function< bool()> > > get_room_edit_methods (RoomPtr room, const Container &rooms)
Получение методов редактирования комнаты
template<typename RoomPtr, typename Container>
enable_if_t< is_base_of_v< Room, typename RoomPtr::element_type > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, void > add_edit_menu_items (vector< MenuObject > &menu, RoomPtr room, const Container &rooms)
Добавление пунктов меню для редактирования комнаты
Detailed Description
Реализация методов работы с комнатами
Author
Kondakov Fedor
Date
2025
Version
1.0
Definition in file kondakov_lr5_methods.hpp.
Function Documentation
add_edit_menu_items()
template<typename RoomPtr, typename Container> enable_if_t< is_base_of_v< Room, typename RoomPtr::element_type > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, void > add_edit_menu_items (vector< MenuObject > & menu, RoomPtr room, const Container & rooms)
Добавление пунктов меню для редактирования комнаты
Template Parameters
RoomPtr Тип указателя на комнату
Container Тип контейнера с комнатами
Parameters
menu Вектор меню для заполнения
room Комната для редактирования
rooms Контейнер с комнатами
Definition at line 144 of file kondakov_lr5_methods.hpp.
References get_room_edit_methods().
Referenced by Methods::edit_room().
get_room_edit_methods()
template<typename RoomPtr, typename Container> enable_if_t< is_base_of_v< Room, typename RoomPtr::element_type > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, vector< function< bool()> > > get_room_edit_methods (RoomPtr room, const Container & rooms)
Получение методов редактирования комнаты
Template Parameters
RoomPtr Тип указателя на комнату
Container Тип контейнера с комнатами
Parameters
room Комната для редактирования
rooms Контейнер с комнатами
Returns
Вектор функций редактирования
Definition at line 62 of file kondakov_lr5_methods.hpp.
References Methods::get_room_numbers().
Referenced by add_edit_menu_items(), and Methods::add_room().