Kondakov_LR5_Hotel: Serializer Namespace Reference
Serializer Namespace Reference
Пространство имён для операций сериализации
Classes
struct RoomTypeRegistry
Регистратор типов комнат для фабричного создания
Functions
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, json > serialize_rooms (const Container &rooms)
Сериализация контейнера комнат в JSON.
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, Container > deserialize_rooms (const json &j)
Десериализация комнат из JSON.
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, void > save_rooms_to_file (const Container &rooms, const string &filename)
Сохранение комнат в файл
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, Container > load_rooms_from_file (const string &filename)
Загрузка комнат из файла
Detailed Description
Пространство имён для операций сериализации
Function Documentation
deserialize_rooms()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, Container > Serializer::deserialize_rooms (const json & j)
Десериализация комнат из JSON.
Template Parameters
Container Тип контейнера для результатов
Parameters
j JSON объект с данными
Returns
Контейнер с десериализованными комнатами
Exceptions
runtime_error При неизвестном типе комнаты
Создает объекты комнат через фабрику на основе типа в JSON
Definition at line 39 of file kondakov_lr5_serializer.hpp.
Referenced by load_rooms_from_file().
load_rooms_from_file()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, Container > Serializer::load_rooms_from_file (const string & filename)
Загрузка комнат из файла
Template Parameters
Container Тип контейнера для результатов
Parameters
filename Имя файла для загрузки
Returns
Контейнер с загруженными комнатами
Exceptions
runtime_error При ошибке открытия файла
Читает JSON из файла и десериализует в объекты комнат
Definition at line 78 of file kondakov_lr5_serializer.hpp.
References deserialize_rooms().
Referenced by main().
save_rooms_to_file()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, void > Serializer::save_rooms_to_file (const Container & rooms, const string & filename)
Сохранение комнат в файл
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер для сохранения
filename Имя файла для сохранения
Exceptions
runtime_error При ошибке открытия файла
Сохраняет JSON-представление в файл с отступами (pretty print)
Definition at line 63 of file kondakov_lr5_serializer.hpp.
References serialize_rooms().
Referenced by main().
serialize_rooms()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, json > Serializer::serialize_rooms (const Container & rooms)
Сериализация контейнера комнат в JSON.
Template Parameters
Container Тип контейнера (должен содержать shared_ptr<Room>)
Parameters
rooms Контейнер с комнатами
Returns
JSON объект с данными комнат
Преобразует каждую комнату в JSON объект с добавлением типа
Definition at line 21 of file kondakov_lr5_serializer.hpp.
Referenced by save_rooms_to_file().