Kondakov_LR5_Hotel: Room Class Reference
Room Class Reference abstract
Иерархия комнат
Абстрактный базовый класс для представления гостиничного номера
#include <kondakov_lr5_room.h>
Public Member Functions
virtual ~Room ()=default
Виртуальный деструктор
operator string () const
Преобразование в строку
virtual string to_string () const
Виртуальный метод преобразования в строку
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, ostream & > friend operator<< (ostream &os, const Container &rooms)
Перегрузка вывода для контейнера комнат
Конструкторы
Room ()
Конструктор по умолчанию
Room (int room_number)
Конструктор преобразования
Room (int room_number, float price_per_night, bool is_booked)
Основной конструктор с параметрами
Room (const Room &)=default
Конструктор копирования
Room & operator= (const Room &)=default
Room (Room &&other) noexcept
Конструктор перемещения
Room & operator= (Room &&) noexcept=default
Геттеры
int get_room_number () const
Получить номер комнаты
float get_price_per_night () const
Получить цену за ночь
bool get_is_booked () const
Получить статус бронирования
virtual const vector< string > & get_amenities () const =0
virtual string get_full_name () const =0
Сеттеры
void set_room_number (int room_number)
Установить номер комнаты
void set_price_per_night (float price_per_night)
Установить цену за ночь
void set_is_booked (bool is_booked)
Установить статус бронирования
Методы ввода
bool input_room_number ()
Ввод номера комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, int >, bool > input_room_number (const Container &room_numbers)
Ввод номера комнаты с проверкой уникальности
bool input_price_per_night ()
Ввод цены за ночь
bool input_is_booked ()
Ввод статуса бронирования
Абстрактные методы
virtual const string & get_room_type () const =0
virtual const string & get_json_type () const =0
virtual float calculate_total (int night_count) const =0
virtual bool validate () const =0
virtual json to_json () const =0
virtual void from_json (const json &j)=0
Static Public Attributes
static const string CURRENCY = "руб."
Валюта для отображения цен
Protected Member Functions
virtual void print () const
Виртуальный метод вывода информации о комнате
virtual bool input ()
Виртуальный метод ввода информации о комнате
Protected Attributes
int room_number
Номер комнаты
float price_per_night
Цена за ночь
bool is_booked
Статус бронирования
Friends
Операторы сравнения
bool operator== (const Room &r1, const Room &r2)
bool operator== (int room_number, const Room &r2)
bool operator== (const Room &r1, int room_number)
bool operator>= (const Room &r1, const Room &r2)
bool operator>= (int room_number, const Room &r2)
bool operator>= (const Room &r1, int room_number)
bool operator<= (const Room &r1, const Room &r2)
bool operator<= (int room_number, const Room &r2)
bool operator<= (const Room &r1, int room_number)
bool operator> (const Room &r1, const Room &r2)
bool operator> (int room_number, const Room &r2)
bool operator> (const Room &r1, int room_number)
bool operator< (const Room &r1, const Room &r2)
bool operator< (int room_number, const Room &r2)
bool operator< (const Room &r1, int room_number)
bool operator!= (const Room &r1, const Room &r2)
bool operator!= (int room_number, const Room &r2)
bool operator!= (const Room &r1, int room_number)
Операторы ввода/вывода
ostream & operator<< (ostream &os, const Room &r)
Оператор вывода
istream & operator>> (istream &is, Room &r)
Оператор ввода
Detailed Description
Абстрактный базовый класс для представления гостиничного номера
Definition at line 25 of file kondakov_lr5_room.h.
Constructor & Destructor Documentation
Room() [1/4]
Room::Room ()
Конструктор по умолчанию
Создает комнату с параметрами:
Номер комнаты: 0
Цена за ночь: 0.0
Статус бронирования: нет
Definition at line 18 of file kondakov_lr5_room.cpp.
References Room().
Referenced by FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), operator<<, operator>>, Room(), Room(), Room(), Room(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), Suite::Suite(), Suite::Suite(), Suite::Suite(), Suite::Suite(), Suite::Suite(), and ~Room().
Room() [2/4]
Room::Room (int room_number)
Конструктор преобразования
Parameters
room_number Номер комнаты
Создает комнату с указанным номером и значениями по умолчанию:
Цена за ночь: 0.0
Статус бронирования: нет
Parameters
room_number Номер комнаты
Definition at line 26 of file kondakov_lr5_room.cpp.
References Room(), and room_number.
Room() [3/4]
Room::Room (int room_number, float price_per_night, bool is_booked)
Основной конструктор с параметрами
Конструктор с параметрами
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
Definition at line 36 of file kondakov_lr5_room.cpp.
References is_booked, price_per_night, and room_number.
Room() [4/4]
Room::Room (Room && other) noexcept
Конструктор перемещения
Parameters
other Другой объект Room
Definition at line 46 of file kondakov_lr5_room.cpp.
References is_booked, price_per_night, Room(), and room_number.
Member Function Documentation
calculate_total()
virtual float Room::calculate_total (int night_count) const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
from_json()
virtual void Room::from_json (const json & j) pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
get_amenities()
virtual const vector< string > & Room::get_amenities () const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
get_full_name()
virtual string Room::get_full_name () const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
get_is_booked()
bool Room::get_is_booked () const inline
Получить статус бронирования
Returns
true если номер забронирован, иначе false
Definition at line 35 of file kondakov_lr5_room.hpp.
References is_booked.
Referenced by ~Room().
get_json_type()
virtual const string & Room::get_json_type () const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
get_price_per_night()
float Room::get_price_per_night () const inline
Получить цену за ночь
Returns
Цена за ночь
Definition at line 27 of file kondakov_lr5_room.hpp.
References price_per_night.
Referenced by ~Room().
get_room_number()
int Room::get_room_number () const inline
Получить номер комнаты
Returns
Номер комнаты
Definition at line 19 of file kondakov_lr5_room.hpp.
References room_number.
Referenced by ~Room().
get_room_type()
virtual const string & Room::get_room_type () const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
input()
virtual bool Room::input () inline protected virtual
Виртуальный метод ввода информации о комнате
Returns
true если операция отменена, false если успешно
Reimplemented in FamilyRoom, StandardRoom, and Suite.
Definition at line 42 of file kondakov_lr5_room.h.
Referenced by FamilyRoom::input(), StandardRoom::input(), and Suite::input().
input_is_booked()
bool Room::input_is_booked () inline
Ввод статуса бронирования
Returns
true если операция отменена, иначе false
Definition at line 108 of file kondakov_lr5_room.hpp.
References InputControl::input(), and is_booked.
Referenced by operator>>, and ~Room().
input_price_per_night()
bool Room::input_price_per_night () inline
Ввод цены за ночь
Returns
true если операция отменена, иначе false
Definition at line 97 of file kondakov_lr5_room.hpp.
References CURRENCY, InputControl::input(), and price_per_night.
Referenced by operator>>, and ~Room().
input_room_number() [1/2]
bool Room::input_room_number () inline
Ввод номера комнаты
Returns
true если операция отменена, иначе false
Definition at line 67 of file kondakov_lr5_room.hpp.
References InputControl::input(), and room_number.
Referenced by operator>>, and ~Room().
input_room_number() [2/2]
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, int >, bool > Room::input_room_number (const Container & room_numbers) inline
Ввод номера комнаты с проверкой уникальности
Template Parameters
Container Тип контейнера с номерами комнат
Parameters
room_numbers Контейнер с существующими номерами комнат
Returns
true если операция отменена, иначе false
Definition at line 80 of file kondakov_lr5_room.hpp.
References InputControl::input(), and room_number.
operator string()
Room::operator string () const explicit
Преобразование в строку
Definition at line 77 of file kondakov_lr5_room.cpp.
References CURRENCY, is_booked, and price_per_night.
operator<<()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, ostream & > friend Room::operator<< (ostream & os, const Container & rooms)
Перегрузка вывода для контейнера комнат
Template Parameters
Container Тип контейнера (должен содержать shared_ptr<Room>)
print()
virtual void Room::print () const inline protected virtual
Виртуальный метод вывода информации о комнате
Reimplemented in FamilyRoom, StandardRoom, and Suite.
Definition at line 34 of file kondakov_lr5_room.h.
set_is_booked()
void Room::set_is_booked (bool is_booked) inline
Установить статус бронирования
Parameters
is_booked Новый статус бронирования
Definition at line 59 of file kondakov_lr5_room.hpp.
References is_booked.
Referenced by ~Room().
set_price_per_night()
void Room::set_price_per_night (float price_per_night) inline
Установить цену за ночь
Parameters
price_per_night Новая цена за ночь
Definition at line 51 of file kondakov_lr5_room.hpp.
References price_per_night.
Referenced by ~Room().
set_room_number()
void Room::set_room_number (int room_number) inline
Установить номер комнаты
Parameters
room_number Новый номер комнаты
Definition at line 43 of file kondakov_lr5_room.hpp.
References room_number.
Referenced by ~Room().
to_json()
virtual json Room::to_json () const pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
to_string()
string Room::to_string () const virtual
Виртуальный метод преобразования в строку
Преобразование в строку
Returns
Строковое представление комнаты
Reimplemented in FamilyRoom, StandardRoom, and Suite.
Definition at line 114 of file kondakov_lr5_room.cpp.
Referenced by FamilyRoom::to_string(), StandardRoom::to_string(), Suite::to_string(), and ~Room().
validate()
virtual bool Room::validate () const inline pure virtual
Implemented in FamilyRoom, StandardRoom, and Suite.
Friends And Related Symbol Documentation
operator!= [1/3]
bool operator!= (const Room & r1, const Room & r2) friend
Definition at line 69 of file kondakov_lr5_room.cpp.
operator!= [2/3]
bool operator!= (const Room & r1, int room_number) friend
Definition at line 71 of file kondakov_lr5_room.cpp.
operator!= [3/3]
bool operator!= (int room_number, const Room & r2) friend
Definition at line 70 of file kondakov_lr5_room.cpp.
operator< [1/3]
bool operator< (const Room & r1, const Room & r2) friend
Definition at line 66 of file kondakov_lr5_room.cpp.
operator< [2/3]
bool operator< (const Room & r1, int room_number) friend
Definition at line 68 of file kondakov_lr5_room.cpp.
operator< [3/3]
bool operator< (int room_number, const Room & r2) friend
Definition at line 67 of file kondakov_lr5_room.cpp.
operator<<
ostream & operator<< (ostream & os, const Room & r) friend
Оператор вывода
Parameters
os Поток вывода
r Комната для вывода
Returns
Поток вывода
Definition at line 91 of file kondakov_lr5_room.cpp.
References Room().
operator<= [1/3]
bool operator<= (const Room & r1, const Room & r2) friend
Definition at line 60 of file kondakov_lr5_room.cpp.
operator<= [2/3]
bool operator<= (const Room & r1, int room_number) friend
Definition at line 62 of file kondakov_lr5_room.cpp.
operator<= [3/3]
bool operator<= (int room_number, const Room & r2) friend
Definition at line 61 of file kondakov_lr5_room.cpp.
operator== [1/3]
bool operator== (const Room & r1, const Room & r2) friend
Definition at line 54 of file kondakov_lr5_room.cpp.
operator== [2/3]
bool operator== (const Room & r1, int room_number) friend
Definition at line 56 of file kondakov_lr5_room.cpp.
operator== [3/3]
bool operator== (int room_number, const Room & r2) friend
Definition at line 55 of file kondakov_lr5_room.cpp.
operator> [1/3]
bool operator> (const Room & r1, const Room & r2) friend
Definition at line 63 of file kondakov_lr5_room.cpp.
operator> [2/3]
bool operator> (const Room & r1, int room_number) friend
Definition at line 65 of file kondakov_lr5_room.cpp.
operator> [3/3]
bool operator> (int room_number, const Room & r2) friend
Definition at line 64 of file kondakov_lr5_room.cpp.
operator>= [1/3]
bool operator>= (const Room & r1, const Room & r2) friend
Definition at line 57 of file kondakov_lr5_room.cpp.
operator>= [2/3]
bool operator>= (const Room & r1, int room_number) friend
Definition at line 59 of file kondakov_lr5_room.cpp.
operator>= [3/3]
bool operator>= (int room_number, const Room & r2) friend
Definition at line 58 of file kondakov_lr5_room.cpp.
operator>>
istream & operator>> (istream & is, Room & r) friend
Оператор ввода
Parameters
is Поток ввода
r Комната для ввода
Returns
Поток ввода
Definition at line 102 of file kondakov_lr5_room.cpp.
References input_is_booked(), input_price_per_night(), input_room_number(), and Room().
Member Data Documentation
CURRENCY
const string Room::CURRENCY = "руб." static
Валюта для отображения цен
Валюта по умолчанию
Definition at line 48 of file kondakov_lr5_room.h.
Referenced by Methods::additional_room_methods(), Methods::calculate_total(), input_price_per_night(), and operator string().
is_booked
bool Room::is_booked protected
Статус бронирования
Definition at line 29 of file kondakov_lr5_room.h.
Referenced by FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::from_json(), StandardRoom::from_json(), Suite::from_json(), get_is_booked(), input_is_booked(), operator string(), Room(), Room(), set_is_booked(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), Suite::Suite(), Suite::Suite(), Suite::Suite(), FamilyRoom::to_json(), StandardRoom::to_json(), Suite::to_json(), and ~Room().
price_per_night
float Room::price_per_night protected
Цена за ночь
Definition at line 28 of file kondakov_lr5_room.h.
Referenced by FamilyRoom::add_play_area(), FamilyRoom::calculate_total(), StandardRoom::calculate_total(), Suite::calculate_total(), StandardRoom::exstra_bed(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::from_json(), StandardRoom::from_json(), Suite::from_json(), get_price_per_night(), input_price_per_night(), operator string(), Suite::order_champagne(), FamilyRoom::remove_play_area(), Room(), Room(), set_price_per_night(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), Suite::Suite(), Suite::Suite(), Suite::Suite(), FamilyRoom::to_json(), StandardRoom::to_json(), Suite::to_json(), and ~Room().
room_number
int Room::room_number protected
Номер комнаты
Definition at line 27 of file kondakov_lr5_room.h.
Referenced by FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::from_json(), StandardRoom::from_json(), Suite::from_json(), FamilyRoom::get_full_name(), StandardRoom::get_full_name(), Suite::get_full_name(), get_room_number(), input_room_number(), input_room_number(), Room(), Room(), Room(), set_room_number(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), StandardRoom::StandardRoom(), Suite::Suite(), Suite::Suite(), Suite::Suite(), Suite::Suite(), FamilyRoom::to_json(), StandardRoom::to_json(), Suite::to_json(), and ~Room().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_room.h
Kondakov_LR5_Hotel/kondakov_lr5_room.cpp
Kondakov_LR5_Hotel/kondakov_lr5_room.hpp