Kondakov_LR5_Hotel: StandardRoom Class Reference
StandardRoom Class Reference final
Класс стандартного номера (наследник Room)
#include <kondakov_lr5_standard_room.h>
Public Member Functions
virtual ~StandardRoom ()=default
Деструктор
void exstra_bed ()
Добавить дополнительную кровать (+20% к цене)
operator string () const
Преобразование в строку
Конструкторы
StandardRoom ()
Конструктор по умолчанию
StandardRoom (int room_number, int bed_count)
Конструктор преобразования
StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv)
Конструктор с удобствами по умолчанию
StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv, string amenities)
Конструктор с параметрами (удобства строка)
StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv, vector< string > amenities)
Конструктор с параметрами (удобства вектор)
StandardRoom (const StandardRoom &)=default
Конструктор копирования
StandardRoom & operator= (const StandardRoom &)=default
StandardRoom (StandardRoom &&other) noexcept
Конструктор перемещения
StandardRoom & operator= (StandardRoom &&) noexcept=default
Геттеры
int get_bed_count () const
Получить количество кроватей
bool get_has_tv () const
Получить наличие телевизора
virtual const vector< string > & get_amenities () const override
Получить список удобств
virtual string get_full_name () const override
Получить полное название комнаты
Сеттеры
void set_bed_count (int bed_count)
Установить количество кроватей
void set_has_tv (bool has_tv)
Установить наличие телевизора
void set_amenities (vector< string > amenities)
Установить список удобств
Методы ввода
bool input_bed_count ()
Ввод количества кроватей
bool input_has_tv ()
Ввод наличия телевизора
template<char Delim>
bool input_amenities ()
Ввод удобств с разделителем
Переопределенные методы
virtual const string & get_room_type () const override
Получить тип комнаты
virtual const string & get_json_type () const override
Получить тип для JSON.
virtual float calculate_total (int night_count) const override
Расчет общей стоимости проживания
virtual bool validate () const override
Проверка валидности номера
JSON методы
virtual json to_json () const override
Преобразование в JSON.
virtual void from_json (const json &j) override
Загрузка из JSON.
Переопределенные методы вывода/ввода
virtual void print () const override
Вывод информации о номере
virtual bool input () override
Ввод информации о номере
virtual string to_string () const override
Преобразование в строку
Public Member Functions inherited from Room
virtual ~Room ()=default
Виртуальный деструктор
operator string () const
Преобразование в строку
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, ostream & > friend operator<< (ostream &os, const Container &rooms)
Перегрузка вывода для контейнера комнат
Room ()
Конструктор по умолчанию
Room (int room_number)
Конструктор преобразования
Room (int room_number, float price_per_night, bool is_booked)
Основной конструктор с параметрами
Room (const Room &)=default
Конструктор копирования
Room & operator= (const Room &)=default
Room (Room &&other) noexcept
Конструктор перемещения
Room & operator= (Room &&) noexcept=default
int get_room_number () const
Получить номер комнаты
float get_price_per_night () const
Получить цену за ночь
bool get_is_booked () const
Получить статус бронирования
void set_room_number (int room_number)
Установить номер комнаты
void set_price_per_night (float price_per_night)
Установить цену за ночь
void set_is_booked (bool is_booked)
Установить статус бронирования
bool input_room_number ()
Ввод номера комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, int >, bool > input_room_number (const Container &room_numbers)
Ввод номера комнаты с проверкой уникальности
bool input_price_per_night ()
Ввод цены за ночь
bool input_is_booked ()
Ввод статуса бронирования
Friends
Операторы сложения удобств
vector< string > operator+ (const StandardRoom &sr1, const StandardRoom &sr2)
vector< string > operator+ (const vector< string > &amenities, const StandardRoom &sr)
vector< string > operator+ (const StandardRoom &sr, const vector< string > &amenities)
vector< string > & operator+= (vector< string > &amenities, const StandardRoom &sr)
StandardRoom & operator+= (StandardRoom &sr, const vector< string > &amenities)
StandardRoom & operator+= (StandardRoom &sr, const string &amenities)
Операторы ввода/вывода
ostream & operator<< (ostream &os, const StandardRoom &r)
Оператор вывода
istream & operator>> (istream &is, StandardRoom &r)
Оператор ввода
Friends inherited from Room
Additional Inherited Members
Static Public Attributes inherited from Room
static const string CURRENCY = "руб."
Валюта для отображения цен
Protected Attributes inherited from Room
int room_number
Номер комнаты
float price_per_night
Цена за ночь
bool is_booked
Статус бронирования
Detailed Description
Класс стандартного номера (наследник Room)
Definition at line 19 of file kondakov_lr5_standard_room.h.
Constructor & Destructor Documentation
StandardRoom() [1/6]
StandardRoom::StandardRoom ()
Конструктор по умолчанию
Создает стандартный номер с параметрами:
Номер комнаты: 0
Цена за ночь: 0.0
Статус бронирования: нет
Количество кроватей: 1
Наличие телевизора: нет
Список удобств: "Wi-Fi", "Air condition"
Definition at line 15 of file kondakov_lr5_standard_room.cpp.
References Room::Room().
Referenced by operator<<, operator>>, StandardRoom(), StandardRoom(), StandardRoom(), and ~StandardRoom().
StandardRoom() [2/6]
StandardRoom::StandardRoom (int room_number, int bed_count)
Конструктор преобразования
Parameters
room_number Номер комнаты
bed_count Количество кроватей
Создает стандартный номер с указанными параметрами и значениями по умолчанию:
Цена за ночь: 0.0
Статус бронирования: нет
Наличие телевизора: нет
Список удобств: "Wi-Fi", "Air condition"
Parameters
room_number Номер комнаты
bed_count Количество кроватей
Definition at line 27 of file kondakov_lr5_standard_room.cpp.
References Room::Room(), and Room::room_number.
StandardRoom() [3/6]
StandardRoom::StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv)
Конструктор с удобствами по умолчанию
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
bed_count Количество кроватей
has_tv Наличие телевизора
Создает стандартный номер с указанными параметрами и удобствами по умолчанию: "Wi-Fi", "Air condition"
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
bed_count Количество кроватей
has_tv Наличие телевизора
Definition at line 42 of file kondakov_lr5_standard_room.cpp.
References Room::is_booked, Room::price_per_night, Room::room_number, and StandardRoom().
StandardRoom() [4/6]
StandardRoom::StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv, string amenities)
Конструктор с параметрами (удобства строка)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
bed_count Количество кроватей
has_tv Наличие телевизора
amenities Удобства (строка, разделитель - запятая)
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
bed_count Количество кроватей
has_tv Наличие телевизора
amenities Удобства (строка с разделителями)
Definition at line 55 of file kondakov_lr5_standard_room.cpp.
References Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
StandardRoom() [5/6]
StandardRoom::StandardRoom (int room_number, float price_per_night, bool is_booked, int bed_count, bool has_tv, vector< string > amenities)
Конструктор с параметрами (удобства вектор)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
bed_count Количество кроватей
has_tv Наличие телевизора
amenities Удобства (вектор строк)
Definition at line 73 of file kondakov_lr5_standard_room.cpp.
References Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
StandardRoom() [6/6]
StandardRoom::StandardRoom (StandardRoom && other) noexcept
Конструктор перемещения
Parameters
other Другой объект StandardRoom
Definition at line 84 of file kondakov_lr5_standard_room.cpp.
References Room::Room(), and StandardRoom().
Member Function Documentation
calculate_total()
float StandardRoom::calculate_total (int night_count) const inline override virtual
Расчет общей стоимости проживания
Parameters
night_count Количество ночей
Returns
Общая стоимость
Implements Room.
Definition at line 126 of file kondakov_lr5_standard_room.hpp.
References Room::price_per_night.
Referenced by ~StandardRoom().
exstra_bed()
void StandardRoom::exstra_bed () inline
Добавить дополнительную кровать (+20% к цене)
Добавить дополнительную кровать
Увеличивает цену на 20% и количество кроватей на 1
Definition at line 142 of file kondakov_lr5_standard_room.hpp.
References Room::price_per_night.
Referenced by ~StandardRoom().
from_json()
void StandardRoom::from_json (const json & j) override virtual
Загрузка из JSON.
Parameters
j JSON объект с данными номера
Implements Room.
Definition at line 110 of file kondakov_lr5_standard_room.cpp.
References Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~StandardRoom().
get_amenities()
const vector< string > & StandardRoom::get_amenities () const inline override virtual
Получить список удобств
Returns
Константная ссылка на вектор удобств
Implements Room.
Definition at line 35 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
get_bed_count()
int StandardRoom::get_bed_count () const inline
Получить количество кроватей
Returns
Количество кроватей
Definition at line 19 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
get_full_name()
string StandardRoom::get_full_name () const inline override virtual
Получить полное название комнаты
Returns
Строка с полным названием комнаты
Implements Room.
Definition at line 43 of file kondakov_lr5_standard_room.hpp.
References Room::room_number.
Referenced by to_string(), and ~StandardRoom().
get_has_tv()
bool StandardRoom::get_has_tv () const inline
Получить наличие телевизора
Returns
true если есть телевизор, иначе false
Definition at line 27 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
get_json_type()
const string & StandardRoom::get_json_type () const inline override virtual
Получить тип для JSON.
Returns
Константная ссылка на строку с типом для JSON
Implements Room.
Definition at line 117 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
get_room_type()
const string & StandardRoom::get_room_type () const inline override virtual
Получить тип комнаты
Returns
Константная ссылка на строку с типом комнаты
Implements Room.
Definition at line 109 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
input()
bool StandardRoom::input () override virtual
Ввод информации о номере
Returns
true если операция отменена, иначе false
Reimplemented from Room.
Definition at line 196 of file kondakov_lr5_standard_room.cpp.
References Room::input().
Referenced by ~StandardRoom().
input_amenities()
template<char Delim> bool StandardRoom::input_amenities () inline
Ввод удобств с разделителем
Template Parameters
Delim Разделитель для ввода
Returns
true если операция отменена, иначе false
Definition at line 97 of file kondakov_lr5_standard_room.hpp.
Referenced by operator>>, and ~StandardRoom().
input_bed_count()
bool StandardRoom::input_bed_count () inline
Ввод количества кроватей
Returns
true если операция отменена, иначе false
Definition at line 77 of file kondakov_lr5_standard_room.hpp.
References InputControl::input().
Referenced by operator>>, and ~StandardRoom().
input_has_tv()
bool StandardRoom::input_has_tv () inline
Ввод наличия телевизора
Returns
true если операция отменена, иначе false
Definition at line 86 of file kondakov_lr5_standard_room.hpp.
References InputControl::input().
Referenced by operator>>, and ~StandardRoom().
operator string()
StandardRoom::operator string () const explicit
Преобразование в строку
Definition at line 153 of file kondakov_lr5_standard_room.cpp.
print()
void StandardRoom::print () const override virtual
Вывод информации о номере
Reimplemented from Room.
Definition at line 188 of file kondakov_lr5_standard_room.cpp.
References to_string().
Referenced by ~StandardRoom().
set_amenities()
void StandardRoom::set_amenities (vector< string > amenities) inline
Установить список удобств
Parameters
amenities Новый список удобств
Definition at line 69 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
set_bed_count()
void StandardRoom::set_bed_count (int bed_count) inline
Установить количество кроватей
Parameters
bed_count Новое количество кроватей
Definition at line 53 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
set_has_tv()
void StandardRoom::set_has_tv (bool has_tv) inline
Установить наличие телевизора
Parameters
has_tv Наличие телевизора
Definition at line 61 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
to_json()
json StandardRoom::to_json () const override virtual
Преобразование в JSON.
Returns
JSON объект с данными номера
Implements Room.
Definition at line 95 of file kondakov_lr5_standard_room.cpp.
References Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~StandardRoom().
to_string()
string StandardRoom::to_string () const override virtual
Преобразование в строку
Returns
Строковое представление номера
Reimplemented from Room.
Definition at line 210 of file kondakov_lr5_standard_room.cpp.
References get_full_name(), and Room::to_string().
Referenced by print(), and ~StandardRoom().
validate()
bool StandardRoom::validate () const inline override virtual
Проверка валидности номера
Returns
true если номер валиден (количество кроватей >= 1), иначе false
Implements Room.
Definition at line 134 of file kondakov_lr5_standard_room.hpp.
Referenced by ~StandardRoom().
Friends And Related Symbol Documentation
operator+ [1/3]
vector< string > operator+ (const StandardRoom & sr, const vector< string > & amenities) friend
Definition at line 131 of file kondakov_lr5_standard_room.cpp.
operator+ [2/3]
vector< string > operator+ (const StandardRoom & sr1, const StandardRoom & sr2) friend
Definition at line 121 of file kondakov_lr5_standard_room.cpp.
operator+ [3/3]
vector< string > operator+ (const vector< string > & amenities, const StandardRoom & sr) friend
Definition at line 126 of file kondakov_lr5_standard_room.cpp.
operator+= [1/3]
StandardRoom & operator+= (StandardRoom & sr, const string & amenities) friend
Definition at line 144 of file kondakov_lr5_standard_room.cpp.
operator+= [2/3]
StandardRoom & operator+= (StandardRoom & sr, const vector< string > & amenities) friend
Definition at line 140 of file kondakov_lr5_standard_room.cpp.
operator+= [3/3]
vector< string > & operator+= (vector< string > & amenities, const StandardRoom & sr) friend
Definition at line 136 of file kondakov_lr5_standard_room.cpp.
operator<<
ostream & operator<< (ostream & os, const StandardRoom & r) friend
Оператор вывода
Parameters
os Поток вывода
sr Комната для вывода
Returns
Поток вывода
Definition at line 167 of file kondakov_lr5_standard_room.cpp.
References StandardRoom().
operator>>
istream & operator>> (istream & is, StandardRoom & r) friend
Оператор ввода
Parameters
is Поток ввода
sr Комната для ввода
Returns
Поток ввода
Definition at line 178 of file kondakov_lr5_standard_room.cpp.
References input_amenities(), input_bed_count(), input_has_tv(), and StandardRoom().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_standard_room.h
Kondakov_LR5_Hotel/kondakov_lr5_standard_room.cpp
Kondakov_LR5_Hotel/kondakov_lr5_standard_room.hpp