Kondakov_LR5_Hotel: ChildCare Class Reference
ChildCare Class Reference
Класс, представляющий услуги по уходу за детьми
#include <kondakov_lr5_child_care.h>
Public Member Functions
~ChildCare ()=default
Деструктор
operator string () const
Преобразование в строку
virtual string to_string () const
Преобразование в строку
Конструкторы
ChildCare ()
Конструктор по умолчанию
ChildCare (bool has_child_care)
Конструктор преобразования
ChildCare (float child_care_price, bool has_child_care)
Основной конструктор с параметрами
ChildCare (const ChildCare &)=default
Конструктор копирования
ChildCare & operator= (const ChildCare &)=default
ChildCare (ChildCare &&other) noexcept
Конструктор перемещения
ChildCare & operator= (ChildCare &&) noexcept=default
Геттеры
float get_child_care_price () const
Получить стоимость услуг для детей
bool get_has_child_care () const
Получить наличие услуг для детей
Сеттеры
void set_child_care_price (float child_care_price)
Установить стоимость услуг для детей
void set_has_child_care (bool has_child_care)
Установить наличие услуг для детей
Методы ввода
bool input_child_care_price ()
Ввод стоимости услуг для детей
bool input_has_child_care ()
Ввод наличия услуг для детей
Static Public Attributes
static const string CURRENCY = "руб."
Валюта для отображения цен
Protected Member Functions
void print () const
Вывод информации об услугах
bool input ()
Ввод информации об услугах
Protected Attributes
float child_care_price
Стоимость услуг для детей (в рублях)
bool has_child_care
Флаг наличия услуг для детей
Friends
Операторы ввода/вывода
ostream & operator<< (ostream &os, const ChildCare &cr)
Оператор вывода
istream & operator>> (istream &is, ChildCare &cr)
Оператор ввода
Detailed Description
Класс, представляющий услуги по уходу за детьми
Definition at line 19 of file kondakov_lr5_child_care.h.
Constructor & Destructor Documentation
ChildCare() [1/4]
ChildCare::ChildCare ()
Конструктор по умолчанию
Создает услуги для детей с параметрами:
Стоимость услуг: 1000.0
Наличие услуг: нет
Definition at line 17 of file kondakov_lr5_child_care.cpp.
References ChildCare().
Referenced by ChildCare(), ChildCare(), ChildCare(), ChildCare(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), operator<<, operator>>, and ~ChildCare().
ChildCare() [2/4]
ChildCare::ChildCare (bool has_child_care)
Конструктор преобразования
Parameters
has_child_care Наличие услуг для детей
Создает услуги для детей с указанным параметром:
Стоимость услуг: 1000.0
Parameters
has_child_care Наличие услуг для детей
Definition at line 25 of file kondakov_lr5_child_care.cpp.
References ChildCare(), and has_child_care.
ChildCare() [3/4]
ChildCare::ChildCare (float child_care_price, bool has_child_care)
Основной конструктор с параметрами
Конструктор с параметрами
Parameters
child_care_price Стоимость услуг
has_child_care Наличие услуг
Definition at line 34 of file kondakov_lr5_child_care.cpp.
References child_care_price, and has_child_care.
ChildCare() [4/4]
ChildCare::ChildCare (ChildCare && other) noexcept
Конструктор перемещения
Parameters
other Другой объект ChildCare
Definition at line 43 of file kondakov_lr5_child_care.cpp.
References child_care_price, ChildCare(), and has_child_care.
Member Function Documentation
get_child_care_price()
float ChildCare::get_child_care_price () const inline
Получить стоимость услуг для детей
Returns
Стоимость услуг в рублях
Definition at line 19 of file kondakov_lr5_child_care.hpp.
References child_care_price.
Referenced by ~ChildCare().
get_has_child_care()
bool ChildCare::get_has_child_care () const inline
Получить наличие услуг для детей
Returns
true если услуги доступны, false если нет
Definition at line 27 of file kondakov_lr5_child_care.hpp.
References has_child_care.
Referenced by ~ChildCare().
input()
bool ChildCare::input () inline protected
Ввод информации об услугах
Returns
true если ввод отменен, false если успешен
Definition at line 35 of file kondakov_lr5_child_care.h.
Referenced by FamilyRoom::input().
input_child_care_price()
bool ChildCare::input_child_care_price () inline
Ввод стоимости услуг для детей
Returns
true если ввод отменен, false если успешен
Definition at line 51 of file kondakov_lr5_child_care.hpp.
References child_care_price, CURRENCY, and InputControl::input().
Referenced by operator>>, and ~ChildCare().
input_has_child_care()
bool ChildCare::input_has_child_care () inline
Ввод наличия услуг для детей
Returns
true если ввод отменен, false если успешен
Definition at line 64 of file kondakov_lr5_child_care.hpp.
References has_child_care, and InputControl::input().
Referenced by operator>>, and ~ChildCare().
operator string()
ChildCare::operator string () const explicit
Преобразование в строку
Returns
Строковое представление услуг
Definition at line 51 of file kondakov_lr5_child_care.cpp.
References child_care_price, CURRENCY, and has_child_care.
print()
void ChildCare::print () const inline protected
Вывод информации об услугах
Definition at line 27 of file kondakov_lr5_child_care.h.
set_child_care_price()
void ChildCare::set_child_care_price (float child_care_price) inline
Установить стоимость услуг для детей
Parameters
child_care_price Новая стоимость услуг
Definition at line 35 of file kondakov_lr5_child_care.hpp.
References child_care_price.
Referenced by ~ChildCare().
set_has_child_care()
void ChildCare::set_has_child_care (bool has_child_care) inline
Установить наличие услуг для детей
Parameters
has_child_care Новое значение наличия услуг
Definition at line 43 of file kondakov_lr5_child_care.hpp.
References has_child_care.
Referenced by ~ChildCare().
to_string()
string ChildCare::to_string () const virtual
Преобразование в строку
Returns
Строковое представление объекта
Reimplemented in FamilyRoom.
Definition at line 85 of file kondakov_lr5_child_care.cpp.
Referenced by FamilyRoom::to_string(), and ~ChildCare().
Friends And Related Symbol Documentation
operator<<
ostream & operator<< (ostream & os, const ChildCare & cr) friend
Оператор вывода
Parameters
os Поток вывода
cr Объект для вывода
Returns
Поток вывода
Definition at line 64 of file kondakov_lr5_child_care.cpp.
References ChildCare().
operator>>
istream & operator>> (istream & is, ChildCare & cr) friend
Оператор ввода
Parameters
is Поток ввода
cr Объект для ввода
Returns
Поток ввода
Definition at line 75 of file kondakov_lr5_child_care.cpp.
References ChildCare(), input_child_care_price(), and input_has_child_care().
Member Data Documentation
child_care_price
float ChildCare::child_care_price protected
Стоимость услуг для детей (в рублях)
Definition at line 21 of file kondakov_lr5_child_care.h.
Referenced by ChildCare(), ChildCare(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::from_json(), get_child_care_price(), input_child_care_price(), operator string(), FamilyRoom::operator[](), FamilyRoom::operator[](), set_child_care_price(), FamilyRoom::to_json(), and ~ChildCare().
CURRENCY
const string ChildCare::CURRENCY = "руб." static
Валюта для отображения цен
Инициализация статического поля
Definition at line 41 of file kondakov_lr5_child_care.h.
Referenced by input_child_care_price(), and operator string().
has_child_care
bool ChildCare::has_child_care protected
Флаг наличия услуг для детей
Definition at line 22 of file kondakov_lr5_child_care.h.
Referenced by ChildCare(), ChildCare(), ChildCare(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::FamilyRoom(), FamilyRoom::from_json(), get_has_child_care(), input_has_child_care(), operator string(), FamilyRoom::operator[](), set_has_child_care(), FamilyRoom::to_json(), and ~ChildCare().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_child_care.h
Kondakov_LR5_Hotel/kondakov_lr5_child_care.cpp
Kondakov_LR5_Hotel/kondakov_lr5_child_care.hpp