Kondakov_LR5_Hotel: Suite Class Reference
Suite Class Reference final
Класс номера люкс, наследующий от Room.
#include <kondakov_lr5_suite.h>
Public Member Functions
virtual ~Suite ()=default
Деструктор
void order_champagne (string amenity)
Заказать шампанское (добавляет услугу)
operator string () const
Преобразование в строку
Конструкторы
Suite ()
Конструктор по умолчанию
Suite (int room_number, bool room_service)
Конструктор преобразования
Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi)
Конструктор с удобствами по умолчанию
Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi, string amenities)
Конструктор с параметрами (удобства строка)
Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi, vector< string > amenities)
Конструктор с параметрами (удобства вектор)
Suite (const Suite &)=default
Конструктор копирования
Suite & operator= (const Suite &)=default
Suite (Suite &&other) noexcept
Конструктор перемещения
Suite & operator= (Suite &&) noexcept=default
Геттеры
bool get_room_service () const
Получить наличие обслуживания
bool get_jacuzzi () const
Получить наличие джакузи
virtual const vector< string > & get_amenities () const override
Получить список удобств
virtual string get_full_name () const override
Получить полное название комнаты
Сеттеры
void set_room_service (bool room_service)
Установить наличие обслуживания
void set_jacuzzi (bool jacuzzi)
Установить наличие джакузи
void set_amenities (vector< string > amenities)
Установить список удобств
Методы ввода
bool input_room_service ()
Ввод наличия обслуживания
bool input_jacuzzi ()
Ввод наличия джакузи
template<char Delim>
bool input_amenities ()
Ввод удобств с разделителем
Переопределенные методы
virtual const string & get_room_type () const override
Получить тип комнаты
virtual const string & get_json_type () const override
Получить тип для JSON.
virtual float calculate_total (int night_count) const override
Расчет общей стоимости проживания
virtual bool validate () const override
Проверка валидности номера
JSON методы
virtual json to_json () const override
Преобразование в JSON.
virtual void from_json (const json &j) override
Загрузка из JSON.
Переопределенные методы вывода/ввода
virtual void print () const override
Вывод информации о номере
virtual bool input () override
Ввод информации о номере
virtual string to_string () const override
Преобразование в строку
Public Member Functions inherited from Room
virtual ~Room ()=default
Виртуальный деструктор
operator string () const
Преобразование в строку
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, ostream & > friend operator<< (ostream &os, const Container &rooms)
Перегрузка вывода для контейнера комнат
Room ()
Конструктор по умолчанию
Room (int room_number)
Конструктор преобразования
Room (int room_number, float price_per_night, bool is_booked)
Основной конструктор с параметрами
Room (const Room &)=default
Конструктор копирования
Room & operator= (const Room &)=default
Room (Room &&other) noexcept
Конструктор перемещения
Room & operator= (Room &&) noexcept=default
int get_room_number () const
Получить номер комнаты
float get_price_per_night () const
Получить цену за ночь
bool get_is_booked () const
Получить статус бронирования
void set_room_number (int room_number)
Установить номер комнаты
void set_price_per_night (float price_per_night)
Установить цену за ночь
void set_is_booked (bool is_booked)
Установить статус бронирования
bool input_room_number ()
Ввод номера комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, int >, bool > input_room_number (const Container &room_numbers)
Ввод номера комнаты с проверкой уникальности
bool input_price_per_night ()
Ввод цены за ночь
bool input_is_booked ()
Ввод статуса бронирования
Friends
Операторы сложения удобств
vector< string > operator+ (const Suite &s1, const Suite &s2)
vector< string > operator+ (const vector< string > &amenities, const Suite &s)
vector< string > operator+ (const Suite &s, const vector< string > &amenities)
vector< string > & operator+= (vector< string > &amenities, const Suite &s)
Suite & operator+= (Suite &s, const vector< string > &amenities)
Suite & operator+= (Suite &s, const string &amenities)
Операторы ввода/вывода
ostream & operator<< (ostream &os, const Suite &r)
Оператор вывода
istream & operator>> (istream &is, Suite &r)
Оператор ввода
Friends inherited from Room
Additional Inherited Members
Static Public Attributes inherited from Room
static const string CURRENCY = "руб."
Валюта для отображения цен
Protected Attributes inherited from Room
int room_number
Номер комнаты
float price_per_night
Цена за ночь
bool is_booked
Статус бронирования
Detailed Description
Класс номера люкс, наследующий от Room.
Представляет номер повышенной комфортности с дополнительными услугами
Definition at line 20 of file kondakov_lr5_suite.h.
Constructor & Destructor Documentation
Suite() [1/6]
Suite::Suite ()
Конструктор по умолчанию
Создает номер люкс с параметрами:
Номер комнаты: 0
Цена за ночь: 0.0
Статус бронирования: нет
Обслуживание в номере: нет
Наличие джакузи: нет
Список удобств: "Lux", "Room service"
Definition at line 15 of file kondakov_lr5_suite.cpp.
References Room::Room().
Referenced by operator<<, operator>>, Suite(), Suite(), Suite(), and ~Suite().
Suite() [2/6]
Suite::Suite (int room_number, bool room_service)
Конструктор преобразования
Parameters
room_number Номер комнаты
room_service Обслуживание в номере
Создает номер люкс с указанными параметрами и значениями по умолчанию:
Цена за ночь: 0.0
Статус бронирования: нет
Наличие джакузи: нет
Список удобств: "Lux", "Room service"
Parameters
room_number Номер комнаты
room_service Наличие обслуживания
Definition at line 27 of file kondakov_lr5_suite.cpp.
References Room::Room(), and Room::room_number.
Suite() [3/6]
Suite::Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi)
Конструктор с удобствами по умолчанию
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Обслуживание в номере
jacuzzi Наличие джакузи
Создает номер люкс с указанными параметрами и удобствами по умолчанию: "Lux", "Room service"
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Наличие обслуживания
jacuzzi Наличие джакузи
Definition at line 42 of file kondakov_lr5_suite.cpp.
References Room::is_booked, Room::price_per_night, Room::room_number, and Suite().
Suite() [4/6]
Suite::Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi, string amenities)
Конструктор с параметрами (удобства строка)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Обслуживание в номере
jacuzzi Наличие джакузи
amenities Удобства (строка, разделитель - запятая)
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Наличие обслуживания
jacuzzi Наличие джакузи
amenities Удобства (строка с разделителями)
Definition at line 55 of file kondakov_lr5_suite.cpp.
References Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
Suite() [5/6]
Suite::Suite (int room_number, float price_per_night, bool is_booked, bool room_service, bool jacuzzi, vector< string > amenities)
Конструктор с параметрами (удобства вектор)
Parameters
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Обслуживание в номере
jacuzzi Наличие джакузи
amenities Удобства (вектор строк)
room_number Номер комнаты
price_per_night Цена за ночь
is_booked Статус бронирования
room_service Наличие обслуживания
jacuzzi Наличие джакузи
amenities Удобства (вектор строк)
Definition at line 73 of file kondakov_lr5_suite.cpp.
References Room::is_booked, Room::price_per_night, Room::Room(), and Room::room_number.
Suite() [6/6]
Suite::Suite (Suite && other) noexcept
Конструктор перемещения
Parameters
other Другой объект Suite
Definition at line 84 of file kondakov_lr5_suite.cpp.
References Room::Room(), and Suite().
Member Function Documentation
calculate_total()
float Suite::calculate_total (int night_count) const inline override virtual
Расчет общей стоимости проживания
Parameters
night_count Количество ночей
Returns
Общая стоимость (цена * ночи + фиксированная плата за услуги)
Implements Room.
Definition at line 126 of file kondakov_lr5_suite.hpp.
References Room::price_per_night.
Referenced by validate(), and ~Suite().
from_json()
void Suite::from_json (const json & j) override virtual
Загрузка из JSON.
Parameters
j JSON объект с данными номера
Implements Room.
Definition at line 110 of file kondakov_lr5_suite.cpp.
References Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~Suite().
get_amenities()
const vector< string > & Suite::get_amenities () const inline override virtual
Получить список удобств
Returns
Константная ссылка на вектор удобств
Implements Room.
Definition at line 35 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
get_full_name()
string Suite::get_full_name () const inline override virtual
Получить полное название комнаты
Returns
Строка с названием формата "Люкс комната №X"
Implements Room.
Definition at line 43 of file kondakov_lr5_suite.hpp.
References Room::room_number.
Referenced by to_string(), and ~Suite().
get_jacuzzi()
bool Suite::get_jacuzzi () const inline
Получить наличие джакузи
Returns
true если есть джакузи, иначе false
Definition at line 27 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
get_json_type()
const string & Suite::get_json_type () const inline override virtual
Получить тип для JSON.
Returns
Константная ссылка на строку с типом
Implements Room.
Definition at line 117 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
get_room_service()
bool Suite::get_room_service () const inline
Получить наличие обслуживания
Returns
true если есть обслуживание, иначе false
Definition at line 19 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
get_room_type()
const string & Suite::get_room_type () const inline override virtual
Получить тип комнаты
Returns
Константная ссылка на строку с типом
Implements Room.
Definition at line 109 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
input()
bool Suite::input () override virtual
Ввод информации о номере
Returns
true если операция отменена, иначе false
Reimplemented from Room.
Definition at line 196 of file kondakov_lr5_suite.cpp.
References Room::input().
Referenced by ~Suite().
input_amenities()
template<char Delim> bool Suite::input_amenities () inline
Ввод удобств с разделителем
Template Parameters
Delim Разделитель для ввода
Returns
true если операция отменена, иначе false
Definition at line 97 of file kondakov_lr5_suite.hpp.
Referenced by operator>>, and ~Suite().
input_jacuzzi()
bool Suite::input_jacuzzi () inline
Ввод наличия джакузи
Returns
true если операция отменена, иначе false
Definition at line 86 of file kondakov_lr5_suite.hpp.
References InputControl::input().
Referenced by operator>>, and ~Suite().
input_room_service()
bool Suite::input_room_service () inline
Ввод наличия обслуживания
Returns
true если операция отменена, иначе false
Definition at line 77 of file kondakov_lr5_suite.hpp.
References InputControl::input().
Referenced by operator>>, and ~Suite().
operator string()
Suite::operator string () const explicit
Преобразование в строку
Definition at line 153 of file kondakov_lr5_suite.cpp.
order_champagne()
void Suite::order_champagne (string amenity) inline
Заказать шампанское (добавляет услугу)
Добавить услугу
Parameters
amenity Название услуги
Увеличивает цену на 2000 руб. и добавляет услугу в список
Definition at line 143 of file kondakov_lr5_suite.hpp.
References InputControl::make_first_letter_uppercase(), and Room::price_per_night.
Referenced by ~Suite().
print()
void Suite::print () const override virtual
Вывод информации о номере
Reimplemented from Room.
Definition at line 188 of file kondakov_lr5_suite.cpp.
References to_string().
Referenced by ~Suite().
set_amenities()
void Suite::set_amenities (vector< string > amenities) inline
Установить список удобств
Parameters
amenities Новый список удобств
Definition at line 69 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
set_jacuzzi()
void Suite::set_jacuzzi (bool jacuzzi) inline
Установить наличие джакузи
Parameters
jacuzzi Новое значение
Definition at line 61 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
set_room_service()
void Suite::set_room_service (bool room_service) inline
Установить наличие обслуживания
Parameters
room_service Новое значение
Definition at line 53 of file kondakov_lr5_suite.hpp.
Referenced by ~Suite().
to_json()
json Suite::to_json () const override virtual
Преобразование в JSON.
Returns
JSON объект с данными номера
Implements Room.
Definition at line 95 of file kondakov_lr5_suite.cpp.
References Room::is_booked, Room::price_per_night, and Room::room_number.
Referenced by ~Suite().
to_string()
string Suite::to_string () const override virtual
Преобразование в строку
Returns
Строковое представление номера
Reimplemented from Room.
Definition at line 210 of file kondakov_lr5_suite.cpp.
References get_full_name(), and Room::to_string().
Referenced by print(), and ~Suite().
validate()
bool Suite::validate () const inline override virtual
Проверка валидности номера
Returns
true если общая стоимость за 1 ночь >= 10000, иначе false
Implements Room.
Definition at line 134 of file kondakov_lr5_suite.hpp.
References calculate_total().
Referenced by ~Suite().
Friends And Related Symbol Documentation
operator+ [1/3]
vector< string > operator+ (const Suite & s, const vector< string > & amenities) friend
Definition at line 131 of file kondakov_lr5_suite.cpp.
operator+ [2/3]
vector< string > operator+ (const Suite & s1, const Suite & s2) friend
Definition at line 121 of file kondakov_lr5_suite.cpp.
operator+ [3/3]
vector< string > operator+ (const vector< string > & amenities, const Suite & s) friend
Definition at line 126 of file kondakov_lr5_suite.cpp.
operator+= [1/3]
Suite & operator+= (Suite & s, const string & amenities) friend
Definition at line 144 of file kondakov_lr5_suite.cpp.
operator+= [2/3]
Suite & operator+= (Suite & s, const vector< string > & amenities) friend
Definition at line 140 of file kondakov_lr5_suite.cpp.
operator+= [3/3]
vector< string > & operator+= (vector< string > & amenities, const Suite & s) friend
Definition at line 136 of file kondakov_lr5_suite.cpp.
operator<<
ostream & operator<< (ostream & os, const Suite & r) friend
Оператор вывода
Parameters
os Поток вывода
sr Комната для вывода
Returns
Поток вывода
Definition at line 167 of file kondakov_lr5_suite.cpp.
References Suite().
operator>>
istream & operator>> (istream & is, Suite & r) friend
Оператор ввода
Parameters
is Поток ввода
s Комната для ввода
Returns
Поток ввода
Definition at line 178 of file kondakov_lr5_suite.cpp.
References input_amenities(), input_jacuzzi(), input_room_service(), and Suite().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_suite.h
Kondakov_LR5_Hotel/kondakov_lr5_suite.cpp
Kondakov_LR5_Hotel/kondakov_lr5_suite.hpp