Kondakov_LR5_Hotel: MenuObject Class Reference
MenuObject Class Reference
Система меню
Класс для представления пункта меню
#include <kondakov_lr5_menu_object.h>
Public Member Functions
MenuObject ()=delete
Удаленный конструктор по умолчанию
~MenuObject ()=default
Деструктор
Конструкторы
MenuObject (int number, string label, function< void()> action)
Конструктор пункта меню без подменю
MenuObject (int number, string label, function< void()> action, bool one_off_menu_inclusion)
Конструктор с флагом одноразового меню
MenuObject (int number, string label, vector< MenuObject > submenu)
Конструктор с подменю
MenuObject (int number, string label, vector< MenuObject > submenu, bool one_off_menu_inclusion)
Конструктор с подменю и флагом
MenuObject (int number, string label, function< void()> action, vector< MenuObject > submenu)
Конструктор с действием и подменю
MenuObject (int number, string label, function< void()> action, vector< MenuObject > submenu, bool one_off_menu_inclusion)
Полный конструктор
template<typename RoomPtr, typename Action, typename = enable_if_t<is_base_of_v<Room, typename RoomPtr::element_type> && is_same_v<bool, decltype(declval<Action>()())>>
MenuObject (int number, string label, RoomPtr room, Action action, string main_message, string success_message)
Конструктор для комнаты с подтверждением
MenuObject (const MenuObject &)=default
Конструктор копирования
MenuObject & operator= (const MenuObject &)=default
MenuObject (MenuObject &&) noexcept
Конструктор перемещения
MenuObject & operator= (MenuObject &&)=default
Методы работы с меню
void show (const string &indentation="") const
Вывод пункта меню
void act () const
Выполнение действия пункта меню
string get_label () const
Получение названия пункта
int get_number () const
Получение номера пункта
string get_full_name () const
Получение полного названия
const vector< MenuObject > & get_submenu () const
Получение подменю
bool get_one_off_menu_inclusion () const
Проверка флага одноразового меню
Static Public Member Functions
Статические методы
template<typename Container>
static enable_if_t< is_same_v< typename Container::value_type, MenuObject >, void > show_menu (const Container &menu, int indent)
Вывод меню
template<typename Container>
static enable_if_t< is_same_v< typename Container::value_type, MenuObject >, void > process (const Container &menu, const string main_label="", const string exit_label="", int indent=0, bool one_off=false)
Обработка взаимодействия с меню
Detailed Description
Класс для представления пункта меню
Реализует древовидную структуру меню с поддержкой подменю и действий
Definition at line 26 of file kondakov_lr5_menu_object.h.
Constructor & Destructor Documentation
MenuObject() [1/8]
MenuObject::MenuObject (int number, string label, function< void()> action)
Конструктор пункта меню без подменю
Parameters
number Номер пункта
label Название пункта
action Действие при выборе
Definition at line 13 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
MenuObject() [2/8]
MenuObject::MenuObject (int number, string label, function< void()> action, bool one_off_menu_inclusion)
Конструктор с флагом одноразового меню
Parameters
number Номер пункта
label Название пункта
action Действие при выборе
one_off_menu_inclusion Флаг одноразового меню
Definition at line 16 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
MenuObject() [3/8]
MenuObject::MenuObject (int number, string label, vector< MenuObject > submenu)
Конструктор с подменю
Parameters
number Номер пункта
label Название пункта
submenu Вектор подменю
Definition at line 19 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
MenuObject() [4/8]
MenuObject::MenuObject (int number, string label, vector< MenuObject > submenu, bool one_off_menu_inclusion)
Конструктор с подменю и флагом
Parameters
number Номер пункта
label Название пункта
submenu Вектор подменю
one_off_menu_inclusion Флаг одноразового меню
Definition at line 22 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
MenuObject() [5/8]
MenuObject::MenuObject (int number, string label, function< void()> action, vector< MenuObject > submenu)
Конструктор с действием и подменю
Parameters
number Номер пункта
label Название пункта
action Действие при выборе
submenu Вектор подменю
Definition at line 25 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
MenuObject() [6/8]
MenuObject::MenuObject (int number, string label, function< void()> action, vector< MenuObject > submenu, bool one_off_menu_inclusion)
Полный конструктор
Parameters
number Номер пункта
label Название пункта
action Действие при выборе
submenu Вектор подменю
one_off_menu_inclusion Флаг одноразового меню
Инициализирует все поля класса
Definition at line 32 of file kondakov_lr5_menu_object.cpp.
MenuObject() [7/8]
template<typename RoomPtr, typename Action, typename> MenuObject::MenuObject (int number, string label, RoomPtr room, Action action, string main_message, string success_message)
Конструктор для комнаты с подтверждением
Template Parameters
RoomPtr Тип умного указателя на Room
Action Тип действия (должен возвращать bool)
Parameters
number Номер пункта
label Название пункта
room Указатель на комнату
action Действие с подтверждением
main_message Сообщение перед действием
success_message Сообщение после успеха
Создает пункт меню с обработкой подтверждения операции
Definition at line 20 of file kondakov_lr5_menu_object.hpp.
References MenuObject().
MenuObject() [8/8]
MenuObject::MenuObject (MenuObject && other) noexcept
Конструктор перемещения
Эффективно переносит ресурсы из другого объекта
Definition at line 41 of file kondakov_lr5_menu_object.cpp.
References MenuObject().
Member Function Documentation
act()
void MenuObject::act () const inline
Выполнение действия пункта меню
Definition at line 44 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
get_full_name()
string MenuObject::get_full_name () const inline
Получение полного названия
Returns
Строка вида "номер. название"
Definition at line 71 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
get_label()
string MenuObject::get_label () const inline
Получение названия пункта
Returns
Название пункта меню
Definition at line 55 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
get_number()
int MenuObject::get_number () const inline
Получение номера пункта
Returns
Номер пункта меню
Definition at line 63 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
get_one_off_menu_inclusion()
bool MenuObject::get_one_off_menu_inclusion () const inline
Проверка флага одноразового меню
Returns
true если меню одноразовое
Definition at line 89 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
get_submenu()
const vector< MenuObject > & MenuObject::get_submenu () const inline
Получение подменю
Returns
Константная ссылка на вектор подменю
Definition at line 81 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
process()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, MenuObject >, void > MenuObject::process (const Container & menu, const string main_label = "", const string exit_label = "", int indent = 0, bool one_off = false) static
Обработка взаимодействия с меню
Template Parameters
Container Тип контейнера с пунктами меню
Parameters
menu Контейнер с меню
main_label Заголовок меню
exit_label Название пункта выхода
indent Уровень вложенности
one_off Флаг одноразового выполнения
Definition at line 121 of file kondakov_lr5_menu_object.hpp.
References InputControl::input(), MenuObject(), process(), and show_menu().
Referenced by Methods::edit_room(), main(), process(), Methods::sort_rooms(), and ~MenuObject().
show()
void MenuObject::show (const string & indentation = "") const inline
Вывод пункта меню
Parameters
indentation Отступ для вложенных пунктов
Definition at line 37 of file kondakov_lr5_menu_object.hpp.
Referenced by ~MenuObject().
show_menu()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, MenuObject >, void > MenuObject::show_menu (const Container & menu, int indent) static
Вывод меню
Template Parameters
Container Тип контейнера с пунктами меню
Parameters
menu Контейнер с меню
indent Уровень вложенности
Definition at line 101 of file kondakov_lr5_menu_object.hpp.
References show_menu().
Referenced by process(), show_menu(), and ~MenuObject().
The documentation for this class was generated from the following files:
Kondakov_LR5_Hotel/kondakov_lr5_menu_object.h
Kondakov_LR5_Hotel/kondakov_lr5_menu_object.cpp
Kondakov_LR5_Hotel/kondakov_lr5_menu_object.hpp