Kondakov_LR5_Hotel: Kondakov_LR5_Hotel/kondakov_lr5_container_operations.hpp File Reference
kondakov_lr5_container_operations.hpp File Reference
Операции с контейнерами строк
#include "kondakov_lr5_input_control.h"
Classes
struct InputControl::DelimitedContainer< Delim, Container &, enable_if_t< is_same_v< typename Container::value_type, string >, void > >
Специализация DelimitedContainer для работы со строками
Functions
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, ostream & > operator<< (ostream &os, const Container &strings)
Перегрузка оператора вывода для контейнера строк
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, Container > operator+ (const Container &lhs, const Container &rhs)
Перегрузка оператора сложения для контейнеров строк
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator+= (Container &lhs, const Container &rhs)
Перегрузка оператора += для контейнеров строк
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator+= (Container &lhs, const string &str)
Перегрузка оператора += для контейнера и строки
template<char Delim, typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, istream & > operator>> (istream &is, InputControl::DelimitedContainer< Delim, Container & > &dc)
Перегрузка оператора ввода для DelimitedContainer.
template<char Delim, typename Container>
enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator>> (InputControl::DelimitedContainer< Delim, Container & > &dc, const string &input_line)
Перегрузка оператора >> для разделения строки в контейнер
Detailed Description
Операции с контейнерами строк
Author
Kondakov Fedor
Date
2025
Version
1.0
Definition in file kondakov_lr5_container_operations.hpp.
Function Documentation
operator+()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, Container > operator+ (const Container & lhs, const Container & rhs)
Перегрузка оператора сложения для контейнеров строк
Template Parameters
Container Тип контейнера (должен содержать строки)
Parameters
lhs Левый операнд
rhs Правый операнд
Returns
Новый контейнер с объединёнными элементами
Объединяет контейнеры, исключая дубликаты
Definition at line 59 of file kondakov_lr5_container_operations.hpp.
operator+=() [1/2]
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator+= (Container & lhs, const Container & rhs)
Перегрузка оператора += для контейнеров строк
Template Parameters
Container Тип контейнера (должен содержать строки)
Parameters
lhs Левый операнд (изменяемый)
rhs Правый операнд
Returns
Ссылка на изменённый контейнер
Добавляет элементы из правого операнда, исключая дубликаты
Definition at line 79 of file kondakov_lr5_container_operations.hpp.
operator+=() [2/2]
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator+= (Container & lhs, const string & str)
Перегрузка оператора += для контейнера и строки
Template Parameters
Container Тип контейнера (должен содержать строки)
Parameters
lhs Левый операнд (изменяемый)
str Добавляемая строка
Returns
Ссылка на изменённый контейнер
Добавляет строку если её ещё нет в контейнере
Definition at line 98 of file kondakov_lr5_container_operations.hpp.
operator<<()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, ostream & > operator<< (ostream & os, const Container & strings)
Перегрузка оператора вывода для контейнера строк
Template Parameters
Container Тип контейнера (должен содержать строки)
Parameters
os Поток вывода
strings Контейнер строк
Returns
Поток вывода
Выводит элементы контейнера через запятую
Definition at line 1 of file kondakov_lr5_container_operations.hpp.
operator>>() [1/2]
template<char Delim, typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, Container & > operator>> (InputControl::DelimitedContainer< Delim, Container & > & dc, const string & input_line)
Перегрузка оператора >> для разделения строки в контейнер
Template Parameters
Delim Разделитель
Container Тип контейнера (должен содержать строки)
Parameters
dc Контейнер с разделителем
input_line Входная строка
Returns
Ссылка на изменённый контейнер
Definition at line 144 of file kondakov_lr5_container_operations.hpp.
References InputControl::split().
operator>>() [2/2]
template<char Delim, typename Container> enable_if_t< is_same_v< typename Container::value_type, string >, istream & > operator>> (istream & is, InputControl::DelimitedContainer< Delim, Container & > & dc)
Перегрузка оператора ввода для DelimitedContainer.
Template Parameters
Delim Разделитель
Container Тип контейнера (должен содержать строки)
Parameters
is Поток ввода
dc Контейнер с разделителем
Returns
Поток ввода
Считывает строку и разделяет её по разделителю в контейнер
Definition at line 116 of file kondakov_lr5_container_operations.hpp.
References InputControl::is_input_empty(), InputControl::split(), and InputControl::trim().