Kondakov_LR5_Hotel: Methods Namespace Reference
Methods Namespace Reference
Функции для работы с комнатами
Пространство имён для операций с комнатами
Classes
struct RoomInfo
Краткая информация о комнате для отображения
Functions
Основные операции с комнатами
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > show_rooms (const Container &rooms)
Вывод списка комнат
template<typename RoomType, typename Container>
enable_if_t< is_base_of_v< Room, typename RoomType > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > add_room (Container &rooms)
Добавление комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > edit_room (Container &rooms)
Изменение комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > delete_room (Container &rooms)
Удаление комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > sort_rooms (Container &rooms)
Сортировка комнат
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > calculate_total (Container &rooms)
Расчёт стоимости проживания
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > validate_room (Container &rooms)
Проверка валидности комнаты
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > additional_room_methods (Container &rooms)
Дополнительные методы комнат
Вспомогательные методы
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, shared_ptr< Room > > get_room_from_rooms_map (string main_label, string message, Container &rooms)
Выбор комнаты из списка
template<typename Container>
enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, vector< int > > get_room_numbers (const Container &rooms)
Получение списка номеров комнат
template<typename RoomType, typename Container>
enable_if_t< is_base_of_v< Room, typename RoomType > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, bool > room_in_rooms_by_room_number (RoomType room, const Container &rooms)
Проверка существования комнаты
Detailed Description
Пространство имён для операций с комнатами
Function Documentation
add_room()
template<typename RoomType, typename Container> enable_if_t< is_base_of_v< Room, typename RoomType > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::add_room (Container & rooms)
Добавление комнаты
Добавление новой комнаты в контейнер
Template Parameters
RoomType Тип добавляемой комнаты
Container Тип контейнера
Parameters
rooms Контейнер для добавления
Returns
Функция для добавления комнаты
Template Parameters
RoomType Тип добавляемой комнаты (StandardRoom/Suite/FamilyRoom)
Container Тип контейнера для хранения комнат
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик добавления комнаты
Вторая функция меню. Создает комнату указанного типа, запрашивает параметры через меню и добавляет в контейнер. Проверяет уникальность номера комнаты.
Definition at line 110 of file kondakov_lr5_methods.hpp.
References get_room_edit_methods().
Referenced by main().
additional_room_methods()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::additional_room_methods (Container & rooms)
Дополнительные методы комнат
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Функция для работы с доп. методами
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик дополнительных операций
Восьмая функция меню. Предоставляет доступ к уникальным функциям каждого типа комнат:
StandardRoom: добавление кровати (+20% к цене)
Suite: заказ шампанского (+2000 к цене)
FamilyRoom: активация игровой зоны (+1500 к цене)
Definition at line 512 of file kondakov_lr5_methods.hpp.
References Room::CURRENCY, get_room_from_rooms_map(), InputControl::input(), and InputControl::yes_or_no().
Referenced by main().
calculate_total()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::calculate_total (Container & rooms)
Расчёт стоимости проживания
Расчет стоимости проживания
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Функция для расчёта
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик расчета стоимости
Шестая функция меню. Запрашивает количество ночей и выводит детализированный расчет с учетом особенностей конкретного типа комнаты.
Definition at line 460 of file kondakov_lr5_methods.hpp.
References Room::CURRENCY, get_room_from_rooms_map(), and InputControl::input().
Referenced by main().
delete_room()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::delete_room (Container & rooms)
Удаление комнаты
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Функция для удаления комнаты
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик удаления комнаты
Четвёртая функция меню. Запрашивает подтверждение перед удалением. При удалении сохраняет целостность нумерации в списке.
Definition at line 301 of file kondakov_lr5_methods.hpp.
References get_room_from_rooms_map(), and InputControl::yes_or_no().
Referenced by main().
edit_room()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::edit_room (Container & rooms)
Изменение комнаты
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Функция для изменения комнаты
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик изменения комнаты
Третья функция меню. Создает динамическое меню для редактирования всех параметров выбранной комнаты с учетом ее конкретного типа
Definition at line 267 of file kondakov_lr5_methods.hpp.
References add_edit_menu_items(), get_room_from_rooms_map(), and MenuObject::process().
Referenced by main().
get_room_from_rooms_map()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, shared_ptr< Room > > Methods::get_room_from_rooms_map (string main_label, string message, Container & rooms)
Выбор комнаты из списка
Выбор комнаты из списка с нумерацией
Template Parameters
Container Тип контейнера
Parameters
main_label Заголовок меню
message Приглашение для ввода
rooms Контейнер с комнатами
Returns
Указатель на выбранную комнату
Template Parameters
Container Тип контейнера с комнатами
Parameters
main_label Заголовок меню выбора
message Приглашение для ввода
rooms Контейнер с комнатами
Returns
Указатель на выбранную комнату или nullptr при отмене
Отображает пронумерованный список всех комнат и возвращает выбранный вариант
Definition at line 597 of file kondakov_lr5_methods.hpp.
References InputControl::input().
Referenced by additional_room_methods(), calculate_total(), delete_room(), edit_room(), and validate_room().
get_room_numbers()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, vector< int > > Methods::get_room_numbers (const Container & rooms)
Получение списка номеров комнат
Получение списка номеров всех комнат
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Вектор номеров комнат
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Вектор номеров комнат
Definition at line 630 of file kondakov_lr5_methods.hpp.
Referenced by get_room_edit_methods(), and room_in_rooms_by_room_number().
room_in_rooms_by_room_number()
template<typename RoomType, typename Container> enable_if_t< is_base_of_v< Room, typename RoomType > &&is_same_v< typename Container::value_type, shared_ptr< Room > >, bool > Methods::room_in_rooms_by_room_number (RoomType room, const Container & rooms)
Проверка существования комнаты
Проверка существования комнаты с указанным номером
Template Parameters
RoomType Тип комнаты
Container Тип контейнера
Parameters
room Проверяемая комната
rooms Контейнер для проверки
Returns
true если комната существует, иначе false
Template Parameters
RoomType Тип комнаты
Container Тип контейнера с комнатами
Parameters
room Комната для проверки
rooms Контейнер с комнатами
Returns
true если комната с таким номером уже существует
< Получение списка номеров комнат
Definition at line 649 of file kondakov_lr5_methods.hpp.
References get_room_numbers().
show_rooms()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::show_rooms (const Container & rooms)
Вывод списка комнат
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция для вывода списка
Template Parameters
Container Тип контейнера (должен содержать shared_ptr<Room>)
Parameters
rooms Контейнер с комнатами
Returns
Функция для вывода списка
Первая функция меню. Выводит форматированный список комнат.
Definition at line 45 of file kondakov_lr5_methods.hpp.
Referenced by main().
sort_rooms()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::sort_rooms (Container & rooms)
Сортировка комнат
Сортировка списка комнат
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер для сортировки
Returns
Функция для сортировки
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик сортировки
Пятая функция меню. Предоставляет подменю с вариантами сортировки:
По номеру комнаты
По типу комнаты
По цене за ночь
По статусу бронирования
Definition at line 344 of file kondakov_lr5_methods.hpp.
References MenuObject::process().
Referenced by main().
validate_room()
template<typename Container> enable_if_t< is_same_v< typename Container::value_type, shared_ptr< Room > >, function< void()> > Methods::validate_room (Container & rooms)
Проверка валидности комнаты
Template Parameters
Container Тип контейнера
Parameters
rooms Контейнер с комнатами
Returns
Функция для проверки
Template Parameters
Container Тип контейнера с комнатами
Parameters
rooms Контейнер с комнатами
Returns
Функция-обработчик проверки валидности
Седьмая функция меню. Проверяет соблюдение бизнес-правил для выбранной комнаты:
Для StandardRoom: количество кроватей >= 1
Для Suite: общая стоимость >= 10000
Для FamilyRoom: детских кроватей <= 4
Definition at line 489 of file kondakov_lr5_methods.hpp.
References get_room_from_rooms_map().
Referenced by main().