Kondakov_LR5_Hotel: InputControl Namespace Reference
InputControl Namespace Reference
Контроль ввода
Пространство имён для функций управления вводом данных
Classes
struct DelimitedContainer
Шаблонный класс для работы с разделителями (базовый шаблон)
struct DelimitedContainer< Delim, Container &, enable_if_t< is_same_v< typename Container::value_type, string >, void > >
Специализация DelimitedContainer для работы со строками
Functions
void trim (string &str)
Удаляет пробелы в начале и конце строки
template<char Delim, typename Container>
void split (const string &input_line, DelimitedContainer< Delim, Container & > &dc)
Разделяет строку на подстроки по разделителю
string get_lowercase (const string str)
Преобразует строку в нижний регистр
void make_first_letter_uppercase (string &str)
Делает первую букву строки заглавной
bool is_input_empty (const string &input)
Проверяет, является ли ввод пустым (для отмены операции)
template<typename T>
bool check_min_max (const T &number, T min, T max)
Проверяет число на вхождение в диапазон
bool input (string &varLink, const string &label)
Функция ввода для строк
bool input (bool &varLink, const string &label)
Функция ввода для bool.
template<typename T>
enable_if_t< is_arithmetic_v< T >, bool > input (T &varLink, const string &label, T min=0, T max=numeric_limits< T >::max())
Функция ввода для чисел
char get_char ()
Получает один символ из ввода
bool yes_or_no (const string &label)
Запрашивает подтверждение (y/n)
Detailed Description
Пространство имён для функций управления вводом данных
Function Documentation
check_min_max()
template<typename T> bool InputControl::check_min_max (const T & number, T min, T max)
Проверяет число на вхождение в диапазон
Template Parameters
T Тип числа
Parameters
number Проверяемое число
min Минимальное значение
max Максимальное значение
Returns
true если число в диапазоне, иначе false
Template Parameters
T Тип числа
Parameters
number Проверяемое число
min Минимальное значение
max Максимальное значение
Returns
true если число в диапазоне, иначе false
Выводит сообщение об ошибке если число вне диапазона
Definition at line 62 of file kondakov_lr5_input_control.hpp.
Referenced by input().
get_char()
char InputControl::get_char ()
Получает один символ из ввода
Returns
Введённый символ
Введённый символ
Очищает буфер ввода после считывания символа
Definition at line 103 of file kondakov_lr5_input_control.cpp.
Referenced by yes_or_no().
get_lowercase()
string InputControl::get_lowercase (const string str)
Преобразует строку в нижний регистр
Parameters
str Входная строка
Returns
Строка в нижнем регистре
Definition at line 31 of file kondakov_lr5_input_control.cpp.
input() [1/3]
bool InputControl::input (bool & varLink, const string & label)
Функция ввода для bool.
Parameters
varLink Ссылка на переменную для сохранения результата
label Подпись для ввода
Returns
true если операция отменена, иначе false
Parameters
varLink Ссылка на переменную для сохранения результата
label Подпись для ввода
Returns
true если операция отменена, иначе false
Использует ввод числа (0 или 1) с последующим преобразованием в bool
Definition at line 89 of file kondakov_lr5_input_control.cpp.
References input().
input() [2/3]
bool InputControl::input (string & varLink, const string & label)
Функция ввода для строк
Parameters
varLink Ссылка на переменную для сохранения результата
label Подпись для ввода
Returns
true если операция отменена, иначе false
Definition at line 68 of file kondakov_lr5_input_control.cpp.
References is_input_empty(), and trim().
Referenced by Methods::additional_room_methods(), Methods::calculate_total(), Methods::get_room_from_rooms_map(), input(), StandardRoom::input_bed_count(), FamilyRoom::input_child_beds(), ChildCare::input_child_care_price(), ChildCare::input_has_child_care(), StandardRoom::input_has_tv(), Room::input_is_booked(), Suite::input_jacuzzi(), Room::input_price_per_night(), Room::input_room_number(), Room::input_room_number(), Suite::input_room_service(), FamilyRoom::input_toy_kit(), is_input_empty(), and MenuObject::process().
input() [3/3]
template<typename T> enable_if_t< is_arithmetic_v< T >, bool > InputControl::input (T & varLink, const string & label, T min = 0, T max = numeric_limits<T>::max())
Функция ввода для чисел
Template Parameters
T Арифметический тип данных
Parameters
varLink Ссылка на переменную для сохранения результата
label Подпись для ввода
min Минимальное значение
max Максимальное значение
Returns
true если операция отменена, иначе false
Template Parameters
T Арифметический тип данных
Parameters
varLink Ссылка на переменную для сохранения результата
label Подпись для ввода
min Минимальное значение
max Максимальное значение
Returns
true если операция отменена, иначе false
Запрашивает ввод пока не будет получено корректное число в заданном диапазоне
Definition at line 86 of file kondakov_lr5_input_control.hpp.
References check_min_max(), is_input_empty(), and trim().
is_input_empty()
bool InputControl::is_input_empty (const string & input)
Проверяет, является ли ввод пустым (для отмены операции)
Parameters
input Входная строка
Returns
true если ввод пустой, иначе false
Parameters
input Входная строка
Returns
true если ввод пустой, иначе false
Выводит сообщение "[Отмена операции]" если ввод пустой
Definition at line 54 of file kondakov_lr5_input_control.cpp.
References input().
Referenced by input(), input(), and operator>>().
make_first_letter_uppercase()
void InputControl::make_first_letter_uppercase (string & str)
Делает первую букву строки заглавной
Parameters
str Строка для обработки
Definition at line 42 of file kondakov_lr5_input_control.cpp.
Referenced by Suite::order_champagne(), and split().
split()
template<char Delim, typename Container> void InputControl::split (const string & input_line, DelimitedContainer< Delim, Container & > & dc)
Разделяет строку на подстроки по разделителю
Template Parameters
Delim Разделитель
Container Тип контейнера для результатов
Parameters
input_line Входная строка
dc Контейнер с разделителем
Template Parameters
Delim Разделитель
Container Тип контейнера для результатов
Parameters
input_line Входная строка
dc Контейнер с разделителем
Очищает целевой контейнер, разделяет строку по разделителю, удаляет пустые элементы, проверяет на дубликаты (без учёта регистра), делает первую букву каждого элемента заглавной
Definition at line 26 of file kondakov_lr5_input_control.hpp.
References make_first_letter_uppercase(), and trim().
Referenced by operator>>(), and operator>>().
trim()
void InputControl::trim (string & str)
Удаляет пробелы в начале и конце строки
Parameters
str Строка для обработки
Definition at line 16 of file kondakov_lr5_input_control.cpp.
Referenced by input(), input(), operator>>(), and split().
yes_or_no()
bool InputControl::yes_or_no (const string & label)
Запрашивает подтверждение (y/n)
Parameters
label Подпись для запроса
Returns
true если введено 'y' или 'Y', false если 'n' или 'N'
Parameters
label Подпись для запроса
Returns
true если введено 'y' или 'Y', false если 'n' или 'N'
Циклически запрашивает ввод пока не будет получен корректный ответ
Definition at line 116 of file kondakov_lr5_input_control.cpp.
References get_char().
Referenced by Methods::additional_room_methods(), and Methods::delete_room().